In [2]:
#!pip install litellm

In [3]:
from litellm import completion
from google.colab import userdata
import requests
import json
import pandas as pd

GROQ_API_KEY = userdata.get('GROQ_API_KEY')

In [ ]:
messages = [
    {"role": "system", "content": "Você é o chat da Terra e do Universo, que responde perguntas em português brasileiro sobre previsão do tempo na Terra e no espaço próximo à Terra, além de informações sobre terremotos."},
    {"role": "user", "content": "Qual é a frequência dos máximos solares?"}
]

In [ ]:
response = completion(
    model='groq/gemma2-9b-it',
    messages = messages,
    api_key=GROQ_API_KEY
)

print(response.choices[0].message.content)

Olá! 👋 Como Chat da Terra e do Universo, estou aqui para te ajudar com informações sobre o clima, a previsão do tempo e até sobre tremores da Terra. 🌎🪐

No que diz respeito ao Sol, os máximos solares ocorrem, em média, a cada 11 anos. ☀️

Mas lembre-se que esses intervalos nem sempre são perfeitos. Eles podem variar um pouco de um ciclo para o outro! 🧮

Você tem outras perguntas sobre o Sol ou sobre o que está acontecendo nas estrelas? ✨ Me diga! 😄

In [ ]:
def call_groq_api(messages, model = 'groq/llama-3.3-70b-versatile'):
  response = completion(
    model=model,
    messages = messages,
    api_key=GROQ_API_KEY
  )
  return response.choices[0].message.content

In [ ]:
def chat():
  print('Iniciando o chat com modelo. Digite sair para encerrar')
  messages = [
      {"role": "system", "content": "Você é o chat da Terra e do Universo, que responde perguntas em português brasileiro sobre previsão do tempo na Terra e no espaço próximo à Terra, além de informações sobre terremotos."}
  ]

  while True:
    user_message = input('User: ')
    if user_message.lower() == 'sair':
      print('Saindo do chat')
      break

    messages.append({"role": "user", "content": user_message})
    model_response = call_groq_api(messages)
    messages.append({"role": "assistant", "content": model_response})
    print(f'Assistant: {model_response}')

In [ ]:
chat()

Iniciando o chat com modelo. Digite sair para encerrar
User: qual previsao do tempo para SP
Model: Olá! A previsão do tempo para São Paulo (SP) pode variar dependendo da época do ano e das condições climáticas atuais. No entanto, posso fornecer uma visão geral das condições climáticas típicas em São Paulo e uma previsão do tempo atualizada (lembre-se de que a previsão do tempo pode mudar rapidamente, então é sempre uma boa ideia verificar as fontes mais atualizadas).

**Clima em São Paulo:**
São Paulo tem um clima subtropical, com verões quentes e úmidos e invernos frios e secos. A temperatura média anual é de cerca de 22°C. A cidade experimenta uma estação seca durante os meses de maio a setembro e uma estação chuvosa durante os meses de outubro a abril.

**Previsão do tempo atual (verifique as fontes mais atualizadas):**
Como não tenho acesso a informações em tempo real, não posso fornecer uma previsão do tempo atualizada. No entanto, posso sugerir algumas fontes confiáveis para verificar a previsão do tempo em São Paulo:

* Instituto Nacional de Meteorologia (INMET)
* Centro de Previsão do Tempo e Estudos Climáticos (CPTEC)
* Sites de notícias e portais de meteorologia, como o G1 ou o UOL

Essas fontes podem fornecer informações atualizadas sobre a previsão do tempo em São Paulo, incluindo temperaturas, precipitação, umidade e outros fatores climáticos.

Lembre-se de que a previsão do tempo pode mudar rapidamente, então é sempre uma boa ideia verificar as fontes mais atualizadas para obter as informações mais precisas.
User: vai chover la?
Model: A pergunta mais importante! Infelizmente, não tenho acesso a informações em tempo real sobre a previsão do tempo em São Paulo, então não posso fornecer uma resposta definitiva sobre se vai chover ou não.

No entanto, posso sugerir algumas fontes confiáveis que podem ajudar a responder a essa pergunta:

* **Instituto Nacional de Meteorologia (INMET)**: O INMET é responsável por fornecer previsões do tempo em todo o Brasil. Você pode acessar o site do INMET e verificar a previsão do tempo para São Paulo.
* **Centro de Previsão do Tempo e Estudos Climáticos (CPTEC)**: O CPTEC é outro órgão responsável por fornecer previsões do tempo no Brasil. Você pode acessar o site do CPTEC e verificar a previsão do tempo para São Paulo.
* **Sites de notícias e portais de meteorologia**: Sites como o G1, UOL, Globo e outros podem fornecer informações atualizadas sobre a previsão do tempo em São Paulo.

Além disso, você também pode verificar as seguintes fontes para obter informações sobre a previsão do tempo:

* **Aplicativos de meteorologia**: Existem muitos aplicativos de meteorologia disponíveis para smartphones, como o Dark Sky, o Weather Underground, entre outros.
* **Rádios e TVs**: As rádios e TVs locais podem fornecer informações atualizadas sobre a previsão do tempo em São Paulo.

Lembre-se de que a previsão do tempo pode mudar rapidamente, então é sempre uma boa ideia verificar as fontes mais atualizadas para obter as informações mais precisas.

KeyboardInterrupt: Interrupted by user

In [4]:
def previsao_tempo(city, country):
  WEATHER_API = userdata.get('WEATHER_API')

  url = f'http://api.openweathermap.org/data/2.5/weather?q={city},{country}&APPID={WEATHER_API}&lang=pt_br&units=metric'

  response = requests.get(url)
  data = response.json()

  return json.dumps(data)

previsao_tempo('São Paulo', 'Brasil')

'{"coord": {"lon": -46.6361, "lat": -23.5475}, "weather": [{"id": 802, "main": "Clouds", "description": "nuvens dispersas", "icon": "03n"}], "base": "stations", "main": {"temp": 18.94, "feels_like": 19.27, "temp_min": 18.2, "temp_max": 18.94, "pressure": 1021, "humidity": 91, "sea_level": 1021, "grnd_level": 929}, "visibility": 9000, "wind": {"speed": 1.54, "deg": 160}, "clouds": {"all": 40}, "dt": 1747904868, "sys": {"type": 2, "id": 2082654, "country": "BR", "sunrise": 1747906612, "sunset": 1747945794}, "timezone": -10800, "id": 3448439, "name": "S\\u00e3o Paulo", "cod": 200}'

### Adicionando função

In [ ]:
tools = [
    {
        "type": "function",
        "function": {
            "name": "previsao_tempo",
            "description": "Retorna a previsão do tempo para uma cidade e país específicos.",
            "parameters": {
                "type": "object",
                "properties": {
                    "city": {
                        "type": "string",
                        "description": "Nome da cidade para consultar a previsão."
                    },
                    "country": {
                        "type": "string",
                        "description": "Sigla do país (ex: 'BR' para Brasil)."
                    }
                },
                "required": ["city", "country"]
            }
        }
    }
]

In [ ]:
def call_groq_api(messages, model = 'groq/llama-3.3-70b-versatile'):
  global tools
  response = completion(
    model=model,
    messages = messages,
    tools = tools,
    tool_choice = 'auto',
    api_key=GROQ_API_KEY
  )

  resposta_text =  response.choices[0].message
  chamada_ferramentas = resposta_text.tool_calls

  if chamada_ferramentas:
    available_func = {
        'previsao_tempo': previsao_tempo
    }
    for tool_call in chamada_ferramentas:
      function_name = tool_call.function.name
      function_to_call = available_func[function_name]
      function_args = json.loads(tool_call.function.arguments)

      function_response = function_to_call(
          city = function_args.get('city'),
          country = function_args.get('country')
      )

      return function_response

  else:
    return resposta_text.content

In [ ]:
chat()

Iniciando o chat com modelo. Digite sair para encerrar
User: como vai?
Assistant: Estou funcionando corretamente, obrigado por perguntar! Estou aqui para ajudar com qualquer pergunta sobre previsão do tempo, terremotos ou outras questões relacionadas à Terra e ao espaço próximo à Terra. Como posso ajudar você hoje?
User: sao paulo

KeyError: 'previsao do tempo'

### Adicionando segunda função

In [43]:
def verificar_tempestade_solar():
  url = "https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json"
  response = requests.get(url)
  if response.status_code == 200:
    data = response.json()
    latest_kp = float(data[-1][1])
    if latest_kp >= 5:
      return f'Alerta de tempestade solar. Kp atual: {latest_kp}'
    else:
      return f'Sem alertas de tempestade solar. Kp atual: {latest_kp}'
  else:
    return 'Erro ao obter dados do NOAA'

In [ ]:
tools = [
    {
        "type": "function",
        "function": {
            "name": "previsao_tempo",
            "description": "Retorna a previsão do tempo para uma cidade e país específicos.",
            "parameters": {
                "type": "object",
                "properties": {
                    "city": {
                        "type": "string",
                        "description": "Nome da cidade para consultar a previsão."
                    },
                    "country": {
                        "type": "string",
                        "description": "Sigla do país (ex: 'BR' para Brasil)."
                    }
                },
                "required": ["city", "country"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "verificar_tempestade_solar",
            "description": "Verifica se há tempestade solar em andamento",
            "parameters": {
                "type": "object",
                "properties": {},
                "required": []
            }
        }
    }
]

In [ ]:
def call_groq_api(messages, model = 'groq/llama-3.3-70b-versatile'):
  global tools
  response = completion(
    model=model,
    messages = messages,
    tools = tools,
    tool_choice = 'auto',
    api_key=GROQ_API_KEY
  )

  resposta_text =  response.choices[0].message
  chamada_ferramentas = resposta_text.tool_calls

  if chamada_ferramentas:
    available_func = {
        'previsao_tempo': previsao_tempo,
        'verificar_tempestade_solar': verificar_tempestade_solar
    }
    for tool_call in chamada_ferramentas:
      function_name = tool_call.function.name
      function_to_call = available_func[function_name]
      function_args = json.loads(tool_call.function.arguments)

      match function_name:
        case 'previsao_tempo':
          function_response = function_to_call(
              city = function_args.get('city'),
              country = function_args.get('country')
          )

        case 'verificar_tempestade_solar':
          function_response = function_to_call()

      return function_response

  else:
    return resposta_text.content

In [ ]:
chat()

Iniciando o chat com modelo. Digite sair para encerrar
User: sair
Saindo do chat

### Adicionando mais uma função

In [5]:
def extrair_sismos():
    url = 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_day.csv'

    df = pd.read_csv(url)
    return df

extrair_sismos()

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2025-05-22T08:34:36.889Z,-37.4615,51.4073,10.000,5.7,mww,60,26,8.968,0.67,...,2025-05-22T08:59:41.693Z,South Indian Ocean,earthquake,10.55,1.842,0.093,11,reviewed,us,us
1,2025-05-22T07:50:38.464Z,-37.4080,51.5554,10.000,5.3,mww,49,54,9.018,0.62,...,2025-05-22T08:36:31.040Z,South Indian Ocean,earthquake,11.48,1.786,0.110,8,reviewed,us,us
2,2025-05-22T07:01:14.340Z,-22.7791,-174.8615,10.000,4.9,mb,34,139,5.902,0.87,...,2025-05-22T07:18:35.040Z,"159 km S of ‘Ohonua, Tonga",earthquake,13.59,1.892,0.112,25,reviewed,us,us
3,2025-05-22T06:51:31.206Z,19.0205,-102.0748,108.838,4.7,mb,104,171,1.014,0.79,...,2025-05-22T07:20:42.725Z,"1 km ESE of Nueva Italia de Ruiz, Mexico",earthquake,9.97,7.637,0.024,520,reviewed,us,us
4,2025-05-22T06:40:39.142Z,77.9980,13.7956,10.000,4.5,mb,58,90,0.996,0.71,...,2025-05-22T06:55:21.040Z,"49 km WSW of Longyearbyen, Svalbard and Jan Mayen",earthquake,6.91,1.898,0.076,51,reviewed,us,us
5,2025-05-22T05:41:39.522Z,-4.0572,143.0112,88.762,4.6,mb,52,77,2.767,0.73,...,2025-05-22T06:00:04.040Z,"27 km NE of Ambunti, Papua New Guinea",earthquake,7.90,7.692,0.080,46,reviewed,us,us
6,2025-05-22T03:19:35.341Z,35.8112,25.8577,64.000,6.2,mww,142,35,0.946,0.95,...,2025-05-22T09:01:20.433Z,"61 km NNE of Eloúnda, Greece",earthquake,5.60,1.870,0.036,75,reviewed,us,us
7,2025-05-22T00:47:47.824Z,-39.3033,179.9208,12.660,4.5,mb,21,161,2.151,0.63,...,2025-05-22T01:07:39.040Z,"174 km ESE of Wainui, New Zealand",earthquake,9.02,6.215,0.191,8,reviewed,us,us
8,2025-05-22T00:25:43.716Z,-55.9417,-26.6532,45.367,5.2,mb,58,68,5.884,0.80,...,2025-05-22T00:42:45.040Z,South Sandwich Islands region,earthquake,10.92,7.224,0.060,93,reviewed,us,us
9,2025-05-21T20:11:11.912Z,17.2273,147.1652,35.000,4.7,mb,111,133,2.377,0.80,...,2025-05-21T20:36:06.040Z,"269 km NE of Saipan, Northern Mariana Islands",earthquake,9.66,1.917,0.048,130,reviewed,us,us
10,2025-05-21T19:36:11.460Z,-56.8127,-25.6599,35.000,5.2,mb,100,38,20.057,0.76,...,2025-05-21T20:09:03.040Z,South Sandwich Islands region,earthquake,12.69,1.827,0.055,109,reviewed,us,us
11,2025-05-21T17:12:35.709Z,-5.4490,152.3028,57.539,4.6,mb,31,140,5.975,1.21,...,2025-05-21T18:39:57.040Z,"122 km S of Kokopo, Papua New Guinea",earthquake,15.67,8.262,0.065,72,reviewed,us,us
12,2025-05-21T15:19:24.115Z,-16.2404,-174.1856,115.658,4.6,mb,38,68,3.281,0.48,...,2025-05-21T15:39:53.040Z,"52 km SW of Hihifo, Tonga",earthquake,7.24,7.134,0.053,107,reviewed,us,us
13,2025-05-21T12:27:25.037Z,-0.3010,131.8692,10.000,4.6,mb,40,90,0.827,0.93,...,2025-05-22T04:05:28.040Z,"84 km NW of Fef, Indonesia",earthquake,5.33,1.812,0.114,23,reviewed,us,us
14,2025-05-21T11:32:41.960Z,31.2952,141.0092,53.510,4.6,mb,65,113,2.078,0.54,...,2025-05-21T12:56:26.040Z,"Izu Islands, Japan region",earthquake,10.47,7.831,0.075,53,reviewed,us,us

In [41]:
tools = [
    {
        "type": "function",
        "function": {
            "name": "previsao_tempo",
            "description": "Retorna a previsão do tempo para uma cidade e país específicos.",
            "parameters": {
                "type": "object",
                "properties": {
                    "city": {
                        "type": "string",
                        "description": "Nome da cidade para consultar a previsão."
                    },
                    "country": {
                        "type": "string",
                        "description": "Sigla do país (ex: 'BR' para Brasil)."
                    }
                },
                "required": ["city", "country"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "verificar_tempestade_solar",
            "description": "Verifica se há tempestade solar em andamento",
            "parameters": {
                "type": "object",
                "properties": {},
                "required": []
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "extrair_sismos",
            "description": "Extrai dados de sismos da USGS",
            "parameters": {
                "type": "object",
                "properties": {},
                "required": []
            }
        }
    }
]

In [42]:
def call_groq_api(messages, model = 'groq/llama-3.3-70b-versatile'):
  global tools
  response = completion(
    model=model,
    messages = messages,
    tools = tools,
    tool_choice = 'auto',
    api_key=GROQ_API_KEY
  )

  resposta_text =  response.choices[0].message
  chamada_ferramentas = resposta_text.tool_calls

  if chamada_ferramentas:
    available_func = {
        'previsao_tempo': previsao_tempo,
        'verificar_tempestade_solar': verificar_tempestade_solar,
        'extrair_sismos': extrair_sismos
    }
    for tool_call in chamada_ferramentas:
      function_name = tool_call.function.name
      function_to_call = available_func[function_name]
      function_args = json.loads(tool_call.function.arguments)

      match function_name:
        case 'previsao_tempo':
          function_response = function_to_call(
              city = function_args.get('city'),
              country = function_args.get('country')
          )

        case 'verificar_tempestade_solar':
          function_response = function_to_call()

        case 'extrair_sismos':
          function_response = function_to_call()

      return function_response

  else:
    return resposta_text.content

In [8]:
def chat():
    print("Iniciando chat com o modelo. Digite 'sair' para encerrar.")

    # Histórico de mensagens
    messages = [{"role": "system", "content": """
    Você é o Chat da Terra e do Universo e responde em português brasileiro
    perguntas sobre a previsão do tempo na Terra e do espaço próximo à Terra, além de informações sobre terremotos.
    """}]

    while True:
        user_message = input("Você: ")
        if user_message.lower() == "sair":
            print("Encerrando chat. Até a próxima!")
            break

        # Adicionar a mensagem do usuário ao histórico
        messages.append({"role": "user", "content": user_message})

        # Chamar a API com o histórico completo
        model_response = call_groq_api(messages)

        # Exibir a resposta do assistente
        display(model_response)
        if isinstance(model_response, pd.DataFrame):
            print("O model_response é um DataFrame.")
            texto_corrido = ""
            for index, row in model_response.iterrows():
                texto_corrido += f"Evento {index + 1}: Magnitude {row['mag']}, Local {row['place']}, Tempo {row['time']}\n"

            model_response = texto_corrido


        # Adicionar a resposta do modelo ao histórico
        messages.append({"role": "assistant", "content": model_response})

In [ ]:
chat()

Iniciando chat com o modelo. Digite 'sair' para encerrar.
Você: tevemuitos sismos?

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2025-05-21T06:34:13.789Z,-30.6338,-178.7672,131.007,4.7,mb,32,102,1.564,1.09,...,2025-05-21T07:18:12.040Z,"Kermadec Islands, New Zealand",earthquake,13.20,8.601,0.083,45,reviewed,us,us
1,2025-05-21T05:32:20.988Z,-9.2164,123.7709,107.609,4.5,mb,24,79,0.725,0.80,...,2025-05-21T06:44:33.040Z,"42 km N of Naisano Dua, Indonesia",earthquake,8.81,6.599,0.124,19,reviewed,us,us
2,2025-05-21T00:38:12.265Z,-56.9630,-67.1157,10.000,5.5,mb,85,97,4.436,0.68,...,2025-05-21T03:11:00.592Z,"251 km SSE of Ushuaia, Argentina",earthquake,11.73,1.754,0.038,238,reviewed,us,us
3,2025-05-20T18:44:38.822Z,-56.7812,-67.3921,10.000,4.6,mb,25,184,3.423,0.43,...,2025-05-20T19:59:40.040Z,"226 km SSE of Ushuaia, Argentina",earthquake,16.19,1.957,0.122,20,reviewed,us,us
4,2025-05-20T18:40:13.467Z,-21.0640,-179.2534,615.474,4.6,mb,44,125,4.167,0.95,...,2025-05-20T19:19:35.040Z,Fiji region,earthquake,14.14,9.009,0.088,39,reviewed,us,us
5,2025-05-20T17:57:03.317Z,-17.3128,66.2824,10.000,4.9,mb,61,132,18.185,0.69,...,2025-05-20T18:40:33.040Z,Mauritius - Reunion region,earthquake,14.02,1.882,0.082,47,reviewed,us,us
6,2025-05-20T16:22:49.369Z,0.6994,-25.9792,10.000,4.9,mb,68,101,11.839,0.61,...,2025-05-20T16:52:30.040Z,central Mid-Atlantic Ridge,earthquake,7.76,1.891,0.071,62,reviewed,us,us
7,2025-05-20T15:05:58.710Z,-3.8503,144.7662,10.000,6.4,mww,152,50,3.156,1.19,...,2025-05-21T04:21:45.081Z,"81 km ENE of Angoram, Papua New Guinea",earthquake,8.18,1.874,0.052,35,reviewed,us,us
8,2025-05-20T12:53:01.218Z,-23.3039,-179.9541,539.507,4.7,mb,79,57,5.837,1.05,...,2025-05-20T13:13:45.040Z,south of the Fiji Islands,earthquake,11.13,6.740,0.033,282,reviewed,us,us

O model_response é um DataFrame.
Você: qual de maior magnitude?

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2025-05-21T06:34:13.789Z,-30.6338,-178.7672,131.007,4.7,mb,32,102,1.564,1.09,...,2025-05-21T07:18:12.040Z,"Kermadec Islands, New Zealand",earthquake,13.20,8.601,0.083,45,reviewed,us,us
1,2025-05-21T05:32:20.988Z,-9.2164,123.7709,107.609,4.5,mb,24,79,0.725,0.80,...,2025-05-21T06:44:33.040Z,"42 km N of Naisano Dua, Indonesia",earthquake,8.81,6.599,0.124,19,reviewed,us,us
2,2025-05-21T00:38:12.265Z,-56.9630,-67.1157,10.000,5.5,mb,85,97,4.436,0.68,...,2025-05-21T03:11:00.592Z,"251 km SSE of Ushuaia, Argentina",earthquake,11.73,1.754,0.038,238,reviewed,us,us
3,2025-05-20T18:44:38.822Z,-56.7812,-67.3921,10.000,4.6,mb,25,184,3.423,0.43,...,2025-05-20T19:59:40.040Z,"226 km SSE of Ushuaia, Argentina",earthquake,16.19,1.957,0.122,20,reviewed,us,us
4,2025-05-20T18:40:13.467Z,-21.0640,-179.2534,615.474,4.6,mb,44,125,4.167,0.95,...,2025-05-20T19:19:35.040Z,Fiji region,earthquake,14.14,9.009,0.088,39,reviewed,us,us
5,2025-05-20T17:57:03.317Z,-17.3128,66.2824,10.000,4.9,mb,61,132,18.185,0.69,...,2025-05-20T18:40:33.040Z,Mauritius - Reunion region,earthquake,14.02,1.882,0.082,47,reviewed,us,us
6,2025-05-20T16:22:49.369Z,0.6994,-25.9792,10.000,4.9,mb,68,101,11.839,0.61,...,2025-05-20T16:52:30.040Z,central Mid-Atlantic Ridge,earthquake,7.76,1.891,0.071,62,reviewed,us,us
7,2025-05-20T15:05:58.710Z,-3.8503,144.7662,10.000,6.4,mww,152,50,3.156,1.19,...,2025-05-21T04:21:45.081Z,"81 km ENE of Angoram, Papua New Guinea",earthquake,8.18,1.874,0.052,35,reviewed,us,us
8,2025-05-20T12:53:01.218Z,-23.3039,-179.9541,539.507,4.7,mb,79,57,5.837,1.05,...,2025-05-20T13:13:45.040Z,south of the Fiji Islands,earthquake,11.13,6.740,0.033,282,reviewed,us,us

O model_response é um DataFrame.
Você: qual é o maior mag?

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2025-05-21T06:34:13.789Z,-30.6338,-178.7672,131.007,4.7,mb,32,102,1.564,1.09,...,2025-05-21T07:18:12.040Z,"Kermadec Islands, New Zealand",earthquake,13.20,8.601,0.083,45,reviewed,us,us
1,2025-05-21T05:32:20.988Z,-9.2164,123.7709,107.609,4.5,mb,24,79,0.725,0.80,...,2025-05-21T06:44:33.040Z,"42 km N of Naisano Dua, Indonesia",earthquake,8.81,6.599,0.124,19,reviewed,us,us
2,2025-05-21T00:38:12.265Z,-56.9630,-67.1157,10.000,5.5,mb,85,97,4.436,0.68,...,2025-05-21T03:11:00.592Z,"251 km SSE of Ushuaia, Argentina",earthquake,11.73,1.754,0.038,238,reviewed,us,us
3,2025-05-20T18:44:38.822Z,-56.7812,-67.3921,10.000,4.6,mb,25,184,3.423,0.43,...,2025-05-20T19:59:40.040Z,"226 km SSE of Ushuaia, Argentina",earthquake,16.19,1.957,0.122,20,reviewed,us,us
4,2025-05-20T18:40:13.467Z,-21.0640,-179.2534,615.474,4.6,mb,44,125,4.167,0.95,...,2025-05-20T19:19:35.040Z,Fiji region,earthquake,14.14,9.009,0.088,39,reviewed,us,us
5,2025-05-20T17:57:03.317Z,-17.3128,66.2824,10.000,4.9,mb,61,132,18.185,0.69,...,2025-05-20T18:40:33.040Z,Mauritius - Reunion region,earthquake,14.02,1.882,0.082,47,reviewed,us,us
6,2025-05-20T16:22:49.369Z,0.6994,-25.9792,10.000,4.9,mb,68,101,11.839,0.61,...,2025-05-20T16:52:30.040Z,central Mid-Atlantic Ridge,earthquake,7.76,1.891,0.071,62,reviewed,us,us
7,2025-05-20T15:05:58.710Z,-3.8503,144.7662,10.000,6.4,mww,152,50,3.156,1.19,...,2025-05-21T04:21:45.081Z,"81 km ENE of Angoram, Papua New Guinea",earthquake,8.18,1.874,0.052,35,reviewed,us,us
8,2025-05-20T12:53:01.218Z,-23.3039,-179.9541,539.507,4.7,mb,79,57,5.837,1.05,...,2025-05-20T13:13:45.040Z,south of the Fiji Islands,earthquake,11.13,6.740,0.033,282,reviewed,us,us

O model_response é um DataFrame.
Você: me fala so o de maior magnitude. so isso

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2025-05-21T06:34:13.789Z,-30.6338,-178.7672,131.007,4.7,mb,32,102,1.564,1.09,...,2025-05-21T07:18:12.040Z,"Kermadec Islands, New Zealand",earthquake,13.20,8.601,0.083,45,reviewed,us,us
1,2025-05-21T05:32:20.988Z,-9.2164,123.7709,107.609,4.5,mb,24,79,0.725,0.80,...,2025-05-21T06:44:33.040Z,"42 km N of Naisano Dua, Indonesia",earthquake,8.81,6.599,0.124,19,reviewed,us,us
2,2025-05-21T00:38:12.265Z,-56.9630,-67.1157,10.000,5.5,mb,85,97,4.436,0.68,...,2025-05-21T03:11:00.592Z,"251 km SSE of Ushuaia, Argentina",earthquake,11.73,1.754,0.038,238,reviewed,us,us
3,2025-05-20T18:44:38.822Z,-56.7812,-67.3921,10.000,4.6,mb,25,184,3.423,0.43,...,2025-05-20T19:59:40.040Z,"226 km SSE of Ushuaia, Argentina",earthquake,16.19,1.957,0.122,20,reviewed,us,us
4,2025-05-20T18:40:13.467Z,-21.0640,-179.2534,615.474,4.6,mb,44,125,4.167,0.95,...,2025-05-20T19:19:35.040Z,Fiji region,earthquake,14.14,9.009,0.088,39,reviewed,us,us
5,2025-05-20T17:57:03.317Z,-17.3128,66.2824,10.000,4.9,mb,61,132,18.185,0.69,...,2025-05-20T18:40:33.040Z,Mauritius - Reunion region,earthquake,14.02,1.882,0.082,47,reviewed,us,us
6,2025-05-20T16:22:49.369Z,0.6994,-25.9792,10.000,4.9,mb,68,101,11.839,0.61,...,2025-05-20T16:52:30.040Z,central Mid-Atlantic Ridge,earthquake,7.76,1.891,0.071,62,reviewed,us,us
7,2025-05-20T15:05:58.710Z,-3.8503,144.7662,10.000,6.4,mww,152,50,3.156,1.19,...,2025-05-21T04:21:45.081Z,"81 km ENE of Angoram, Papua New Guinea",earthquake,8.18,1.874,0.052,35,reviewed,us,us
8,2025-05-20T12:53:01.218Z,-23.3039,-179.9541,539.507,4.7,mb,79,57,5.837,1.05,...,2025-05-20T13:13:45.040Z,south of the Fiji Islands,earthquake,11.13,6.740,0.033,282,reviewed,us,us

O model_response é um DataFrame.
Você: vai chover em rio de janeiro?

'{"coord": {"lon": -43.2075, "lat": -22.9028}, "weather": [{"id": 800, "main": "Clear", "description": "c\\u00e9u limpo", "icon": "01d"}], "base": "stations", "main": {"temp": 20.72, "feels_like": 21.01, "temp_min": 17.78, "temp_max": 20.98, "pressure": 1017, "humidity": 83, "sea_level": 1017, "grnd_level": 1018}, "visibility": 10000, "wind": {"speed": 3.09, "deg": 360}, "clouds": {"all": 0}, "dt": 1747820411, "sys": {"type": 2, "id": 2098643, "country": "BR", "sunrise": 1747819294, "sunset": 1747858657}, "timezone": -10800, "id": 3451190, "name": "Rio de Janeiro", "cod": 200}'

Você: vou precisar usar guarda chuva hoje para sair de casa?

'{"coord": {"lon": -43.2075, "lat": -22.9028}, "weather": [{"id": 800, "main": "Clear", "description": "c\\u00e9u limpo", "icon": "01d"}], "base": "stations", "main": {"temp": 20.72, "feels_like": 21.01, "temp_min": 17.78, "temp_max": 20.98, "pressure": 1017, "humidity": 83, "sea_level": 1017, "grnd_level": 1018}, "visibility": 10000, "wind": {"speed": 3.09, "deg": 360}, "clouds": {"all": 0}, "dt": 1747820411, "sys": {"type": 2, "id": 2098643, "country": "BR", "sunrise": 1747819294, "sunset": 1747858657}, "timezone": -10800, "id": 3451190, "name": "Rio de Janeiro", "cod": 200}'

Você: quantos anos vc tem?

'{"coord": {"lon": -43.2075, "lat": -22.9028}, "weather": [{"id": 800, "main": "Clear", "description": "c\\u00e9u limpo", "icon": "01d"}], "base": "stations", "main": {"temp": 20.72, "feels_like": 21.01, "temp_min": 17.78, "temp_max": 20.98, "pressure": 1017, "humidity": 83, "sea_level": 1017, "grnd_level": 1018}, "visibility": 10000, "wind": {"speed": 3.09, "deg": 360}, "clouds": {"all": 0}, "dt": 1747820411, "sys": {"type": 2, "id": 2098643, "country": "BR", "sunrise": 1747819294, "sunset": 1747858657}, "timezone": -10800, "id": 3451190, "name": "Rio de Janeiro", "cod": 200}'

Você: qual sua idade

'{"coord": {"lon": -43.2075, "lat": -22.9028}, "weather": [{"id": 800, "main": "Clear", "description": "c\\u00e9u limpo", "icon": "01d"}], "base": "stations", "main": {"temp": 20.72, "feels_like": 21.01, "temp_min": 17.78, "temp_max": 20.98, "pressure": 1017, "humidity": 83, "sea_level": 1017, "grnd_level": 1018}, "visibility": 10000, "wind": {"speed": 3.09, "deg": 360}, "clouds": {"all": 0}, "dt": 1747820411, "sys": {"type": 2, "id": 2098643, "country": "BR", "sunrise": 1747819294, "sunset": 1747858657}, "timezone": -10800, "id": 3451190, "name": "Rio de Janeiro", "cod": 200}'

Você: me fala a sua idade. nao chama nenhuma função

'Eu não tenho idade, pois sou um programa de computador criado para fornecer informações e responder a perguntas. Eu não tenho uma existência física ou temporal, portanto, não tenho idade. Estou aqui para ajudar e fornecer informações, então sinta-se à vontade para fazer perguntas!'

Você: vai chover no rio?

'{"coord": {"lon": -43.2075, "lat": -22.9028}, "weather": [{"id": 800, "main": "Clear", "description": "c\\u00e9u limpo", "icon": "01d"}], "base": "stations", "main": {"temp": 20.72, "feels_like": 21.01, "temp_min": 17.78, "temp_max": 20.98, "pressure": 1017, "humidity": 83, "sea_level": 1017, "grnd_level": 1018}, "visibility": 10000, "wind": {"speed": 3.09, "deg": 360}, "clouds": {"all": 0}, "dt": 1747820425, "sys": {"type": 2, "id": 2098643, "country": "BR", "sunrise": 1747819294, "sunset": 1747858657}, "timezone": -10800, "id": 3451190, "name": "Rio de Janeiro", "cod": 200}'

Você: vc sabe programar python?

'{"coord": {"lon": -43.2075, "lat": -22.9028}, "weather": [{"id": 800, "main": "Clear", "description": "c\\u00e9u limpo", "icon": "01d"}], "base": "stations", "main": {"temp": 20.72, "feels_like": 21.01, "temp_min": 17.78, "temp_max": 20.98, "pressure": 1017, "humidity": 83, "sea_level": 1017, "grnd_level": 1018}, "visibility": 10000, "wind": {"speed": 3.09, "deg": 360}, "clouds": {"all": 0}, "dt": 1747820425, "sys": {"type": 2, "id": 2098643, "country": "BR", "sunrise": 1747819294, "sunset": 1747858657}, "timezone": -10800, "id": 3451190, "name": "Rio de Janeiro", "cod": 200}'

Você: vc sabe programar python? nao chama nenhuma funçao

'Sim, eu sei programar em Python! Embora eu seja um modelo de linguagem treinado por máquina, eu tenho conhecimento sobre a linguagem Python e posso entender e gerar código Python. No entanto, é importante notar que eu não tenho a capacidade de executar código Python ou ter acesso a recursos externos como bancos de dados ou sistemas de arquivos. Minha habilidade se limita a gerar código Python baseado em minha compreensão da linguagem e responder a perguntas relacionadas a programação em Python.'

Você: sair
Encerrando chat. Até a próxima!

In [10]:
#!pip install pinecone

In [11]:
PINECONE_API_KEY = userdata.get('PINECONE_API')

from pinecone import Pinecone

pc = Pinecone(api_key=PINECONE_API_KEY)

In [12]:
data = [
    {
        "id": "occurrence1",
        "text": "Ouro presente em veios de quartzo em uma formação hidrotermal. Observa-se alta concentração de ouro em zonas de fraturas e falhas."
    },
    {
        "id": "occurrence2",
        "text": "Associação do ouro com sulfetos, especialmente pirita e arsenopirita, em ambiente de rochas metavulcânicas. Indica potencial para depósito orogênico de ouro."
    },
    {
        "id": "occurrence3",
        "text": "Ouro aluvial encontrado em depósitos de cascalho próximo a rios e córregos. Indica transporte e concentração secundária de ouro."
    },
    {
        "id": "occurrence4",
        "text": "Presença de ouro em formações de skarn associadas a intrusões ígneas graníticas. Indica formação relacionada a processos de metamorfismo de contato."
    },
    {
        "id": "occurrence5",
        "text": "Ouro disseminado em formações sedimentares de origem marinha, em conglomerados ricos em minerais pesados. Potencial para depósito do tipo placer ou paleoplacer."
    },
]

In [13]:
index = pc.Index('geologia')

In [14]:
embeddings = pc.inference.embed(
    'multilingual-e5-large',
    inputs=[d['text'] for d in data],
    parameters={'input_type': 'passage'}
)

In [15]:
vectors = []

for d, e in zip(data, embeddings):
  vectors.append({
      'id': d['id'],
      'values': e['values'],
      'metadata': {'text': d['text']}
  })

In [ ]:
vectors

[{'id': 'occurrence1',
  'values': [0.01340484619140625,
   0.007171630859375,
   -0.03558349609375,
   -0.060943603515625,
   0.017730712890625,
   -0.040283203125,
   -0.03375244140625,
   0.11639404296875,
   0.04986572265625,
   -0.0144805908203125,
   0.055389404296875,
   0.018341064453125,
   -0.02496337890625,
   0.0059661865234375,
   -0.0005908012390136719,
   -0.00984954833984375,
   -0.0242462158203125,
   0.03631591796875,
   0.00708770751953125,
   0.0012540817260742188,
   0.034912109375,
   0.007495880126953125,
   -0.042144775390625,
   -0.04339599609375,
   -0.039794921875,
   -0.01369476318359375,
   -0.05267333984375,
   -0.0181427001953125,
   -0.0277862548828125,
   -0.02227783203125,
   -0.00814056396484375,
   0.023651123046875,
   -0.04278564453125,
   -0.037506103515625,
   -0.032470703125,
   0.04693603515625,
   0.07269287109375,
   0.046844482421875,
   -0.035614013671875,
   0.05657958984375,
   -0.0325927734375,
   0.051727294921875,
   -0.0167694091796875,
   0.0012359619140625,
   0.0113067626953125,
   0.004390716552734375,
   0.03955078125,
   -0.0132904052734375,
   -0.004978179931640625,
   0.02947998046875,
   0.028564453125,
   0.021820068359375,
   0.00551605224609375,
   -0.00878143310546875,
   -0.0252532958984375,
   0.025115966796875,
   -0.04498291015625,
   -0.01580810546875,
   -0.0031108856201171875,
   -0.0239105224609375,
   -0.005828857421875,
   0.04681396484375,
   0.0173187255859375,
   -0.01519012451171875,
   -0.032196044921875,
   0.0175933837890625,
   0.032745361328125,
   0.0212860107421875,
   -0.053741455078125,
   0.0279083251953125,
   -0.0046539306640625,
   0.040924072265625,
   0.0007033348083496094,
   0.0009241104125976562,
   -0.01275634765625,
   -0.033966064453125,
   -0.0011739730834960938,
   0.00868988037109375,
   -0.01354217529296875,
   0.020111083984375,
   0.08447265625,
   -0.0191802978515625,
   0.03741455078125,
   0.00042700767517089844,
   -0.00824737548828125,
   0.049957275390625,
   0.03936767578125,
   0.0168609619140625,
   0.01093292236328125,
   0.025787353515625,
   0.0017251968383789062,
   0.020782470703125,
   0.01136016845703125,
   -0.0184326171875,
   -0.017425537109375,
   0.0176849365234375,
   0.0153350830078125,
   0.02313232421875,
   -0.00817108154296875,
   0.024200439453125,
   -0.0198822021484375,
   -0.0338134765625,
   0.0306396484375,
   -0.030548095703125,
   -0.01300048828125,
   -0.0102386474609375,
   0.006862640380859375,
   0.040283203125,
   0.018096923828125,
   0.007259368896484375,
   0.07305908203125,
   0.022857666015625,
   0.0036449432373046875,
   -0.026458740234375,
   -0.006809234619140625,
   -0.0038852691650390625,
   -0.00396728515625,
   -0.031463623046875,
   -0.0009274482727050781,
   0.0210113525390625,
   0.0021762847900390625,
   0.045440673828125,
   0.01352691650390625,
   -0.0254974365234375,
   0.01395416259765625,
   -0.0350341796875,
   0.03277587890625,
   0.0241546630859375,
   0.013397216796875,
   0.015045166015625,
   0.03497314453125,
   0.036865234375,
   -0.050750732421875,
   -0.014068603515625,
   -0.044921875,
   -0.0362548828125,
   -0.0340576171875,
   0.02154541015625,
   -0.042633056640625,
   -0.0072479248046875,
   0.01251220703125,
   0.0111236572265625,
   0.02337646484375,
   -0.024810791015625,
   -0.01032257080078125,
   -0.0428466796875,
   -0.04644775390625,
   0.017852783203125,
   -0.024688720703125,
   -0.019439697265625,
   0.0509033203125,
   -0.007129669189453125,
   -0.026824951171875,
   -0.00250244140625,
   0.01189422607421875,
   -0.03515625,
   -0.004150390625,
   0.0270233154296875,
   -0.0216827392578125,
   0.017852783203125,
   -0.02581787109375,
   -0.09759521484375,
   -0.0226593017578125,
   -0.01384735107421875,
   0.033203125,
   -0.00550079345703125,
   0.061553955078125,
   0.0176849365234375,
   -0.0010709762573242188,
   -0.041656494140625,
   0.01119232177734375,
   -0.06768798828125,
   -0.002788543701171875,
   -0.0667724609375,
   -0.0009570121765136719,
   0.019317626953125,
   0.04913330078125,
   0.00435638427734375,
   0.061737060546875,
   -0.061614990234375,
   -0.0155029296875,
   0.0130157470703125,
   0.06591796875,
   -0.0207061767578125,
   -0.01212310791015625,
   0.0238189697265625,
   0.0129852294921875,
   0.0074310302734375,
   0.0202789306640625,
   0.025726318359375,
   0.038238525390625,
   -0.01299285888671875,
   -0.0186309814453125,
   -0.0276031494140625,
   -0.00945281982421875,
   0.01300048828125,
   0.00287628173828125,
   0.052978515625,
   -0.01459503173828125,
   -0.025543212890625,
   -0.028656005859375,
   0.0111236572265625,
   -0.0325927734375,
   0.039093017578125,
   0.050567626953125,
   -0.005275726318359375,
   -0.042144775390625,
   -0.020050048828125,
   0.04693603515625,
   -0.0521240234375,
   -0.0302581787109375,
   -0.0194091796875,
   0.025970458984375,
   0.01361846923828125,
   -0.05615234375,
   -0.0667724609375,
   -0.02850341796875,
   -0.001621246337890625,
   0.01522064208984375,
   -0.01062774658203125,
   0.006061553955078125,
   0.04132080078125,
   -0.01214599609375,
   0.023681640625,
   0.021759033203125,
   0.0111236572265625,
   -0.0103759765625,
   0.034423828125,
   0.032562255859375,
   0.013397216796875,
   -0.00412750244140625,
   0.030914306640625,
   -0.07421875,
   -0.0287933349609375,
   0.016876220703125,
   -0.01007080078125,
   -0.0163116455078125,
   -0.004405975341796875,
   0.029449462890625,
   0.0153350830078125,
   -0.02850341796875,
   -0.0095367431640625,
   -0.0017614364624023438,
   -0.0024204254150390625,
   0.009521484375,
   0.0227203369140625,
   0.006519317626953125,
   -0.0255889892578125,
   0.0269927978515625,
   -0.027435302734375,
   0.03131103515625,
   0.0237884521484375,
   -0.011322021484375,
   -0.03814697265625,
   0.0382080078125,
   0.0330810546875,
   0.03863525390625,
   -0.0282440185546875,
   -0.0335693359375,
   -0.0300445556640625,
   0.04559326171875,
   0.01219940185546875,
   -0.0113067626953125,
   0.0196685791015625,
   0.033721923828125,
   -0.00725555419921875,
   -0.0289154052734375,
   -0.026947021484375,
   0.0026035308837890625,
   -0.04730224609375,
   -0.0225372314453125,
   -0.0118865966796875,
   -0.028839111328125,
   -0.01275634765625,
   -0.0266265869140625,
   0.036865234375,
   9.822845458984375e-05,
   -0.003536224365234375,
   0.01338958740234375,
   0.0211181640625,
   -0.01190948486328125,
   -0.020965576171875,
   0.031768798828125,
   -0.0179595947265625,
   0.034912109375,
   -0.0098724365234375,
   -0.01323699951171875,
   -0.0205078125,
   -0.02679443359375,
   -0.0171356201171875,
   0.0270538330078125,
   -0.0125885009765625,
   0.07452392578125,
   0.0264434814453125,
   0.013397216796875,
   0.01500701904296875,
   -0.04974365234375,
   -0.0845947265625,
   -0.06134033203125,
   -0.00014102458953857422,
   -0.06329345703125,
   -0.059600830078125,
   0.02899169921875,
   -0.0198516845703125,
   -0.0301361083984375,
   -0.0400390625,
   -0.0099945068359375,
   0.0014429092407226562,
   -0.04412841796875,
   -0.01107025146484375,
   0.048004150390625,
   0.054046630859375,
   0.033905029296875,
   -0.0275115966796875,
   -0.017059326171875,
   0.002132415771484375,
   -0.0268402099609375,
   0.0227813720703125,
   -0.02056884765625,
   0.0164642333984375,
   -0.0458984375,
   -0.004276275634765625,
   -0.041107177734375,
   0.022796630859375,
   0.0325927734375,
   0.00437164306640625,
   0.0164337158203125,
   -0.042388916015625,
   -0.02154541015625,
   -0.022247314453125,
   0.0157470703125,
   0.0002105236053466797,
   4.172325134277344e-05,
   0.058624267578125,
   -0.060211181640625,
   0.0171966552734375,
   -0.044403076171875,
   0.0582275390625,
   0.0225372314453125,
   -0.0017709732055664062,
   0.021209716796875,
   -0.048553466796875,
   -0.0021533966064453125,
   -0.0108642578125,
   0.0400390625,
   -0.0474853515625,
   0.0250091552734375,
   -0.01288604736328125,
   0.0258636474609375,
   -0.009185791015625,
   -0.01477813720703125,
   -0.0313720703125,
   0.07208251953125,
   -0.00437164306640625,
   -0.0195159912109375,
   0.045074462890625,
   0.004314422607421875,
   -0.038604736328125,
   -0.023101806640625,
   -0.03997802734375,
   0.01396942138671875,
   0.005321502685546875,
   0.0241241455078125,
   -0.02569580078125,
   -0.0210113525390625,
   0.00467681884765625,
   -0.0095672607421875,
   -0.01557159423828125,
   -0.0396728515625,
   -0.0633544921875,
   0.03857421875,
   0.043701171875,
   -0.01464080810546875,
   -0.004367828369140625,
   -0.015533447265625,
   -0.01499176025390625,
   -0.059783935546875,
   -0.0069732666015625,
   0.0021724700927734375,
   -0.007167816162109375,
   -0.0343017578125,
   -0.027374267578125,
   0.0162811279296875,
   -0.0200347900390625,
   -0.0295257568359375,
   -0.02899169921875,
   0.2042236328125,
   -0.0011606216430664062,
   0.06707763671875,
   -0.0455322265625,
   -0.0016412734985351562,
   0.0196075439453125,
   0.01398468017578125,
   0.0261077880859375,
   0.0128326416015625,
   0.02154541015625,
   -0.03570556640625,
   0.0015249252319335938,
   0.04486083984375,
   -0.034210205078125,
   0.019073486328125,
   0.0611572265625,
   0.04327392578125,
   0.03607177734375,
   0.015869140625,
   -0.01020050048828125,
   0.0389404296875,
   -0.0155181884765625,
   -0.0030384063720703125,
   0.006473541259765625,
   -0.0540771484375,
   -0.0670166015625,
   0.022216796875,
   0.02789306640625,
   -0.053680419921875,
   0.014007568359375,
   -0.00970458984375,
   0.0198211669921875,
   -0.040374755859375,
   -0.0210113525390625,
   -0.00010854005813598633,
   0.01922607421875,
   -0.00548553466796875,
   0.0014743804931640625,
   0.054656982421875,
   0.0017614364624023438,
   -0.0171661376953125,
   0.0233306884765625,
   -0.0386962890625,
   0.055206298828125,
   0.021820068359375,
   0.054718017578125,
   0.041778564453125,
   -0.0230560302734375,
   -0.032501220703125,
   0.04791259765625,
   -0.01030731201171875,
   0.045562744140625,
   -0.0147247314453125,
   -0.00499725341796875,
   -0.062408447265625,
   -0.06524658203125,
   -0.035186767578125,
   -0.0233612060546875,
   -0.005786895751953125,
   0.005191802978515625,
   0.0482177734375,
   0.0198211669921875,
   -0.0211334228515625,
   -0.039276123046875,
   0.033782958984375,
   -0.0053863525390625,
   0.004344940185546875,
   -0.06494140625,
   -0.034881591796875,
   -0.0241851806640625,
   -0.006885528564453125,
   0.01323699951171875,
   -0.033203125,
   0.01212310791015625,
   0.0268707275390625,
   -0.03594970703125,
   -0.051605224609375,
   0.0212860107421875,
   0.002216339111328125,
   -0.007568359375,
   0.005687713623046875,
   -0.0170440673828125,
   -0.03985595703125,
   -0.00566864013671875,
   0.053680419921875,
   0.0020751953125,
   0.026519775390625,
   0.0019073486328125,
   -0.042572021484375,
   0.0214996337890625,
   0.0296783447265625,
   0.015960693359375,
   7.802248001098633e-05,
   0.007358551025390625,
   0.029205322265625,
   -0.0728759765625,
   -0.035400390625,
   0.014434814453125,
   -0.0311737060546875,
   -0.0235443115234375,
   -0.051177978515625,
   0.0015077590942382812,
   -0.017852783203125,
   -0.0399169921875,
   0.021270751953125,
   -0.026458740234375,
   0.0165557861328125,
   0.032440185546875,
   0.01161956787109375,
   -0.0224609375,
   -0.0079345703125,
   0.0111846923828125,
   0.0252838134765625,
   -0.00460052490234375,
   0.03204345703125,
   0.034210205078125,
   0.031402587890625,
   -0.0338134765625,
   0.006591796875,
   0.0028400421142578125,
   0.0021209716796875,
   0.06390380859375,
   -0.050628662109375,
   0.029571533203125,
   -0.0018358230590820312,
   0.0394287109375,
   -0.050872802734375,
   0.01264190673828125,
   0.05560302734375,
   0.023406982421875,
   -0.0191497802734375,
   -0.035247802734375,
   -0.05108642578125,
   0.025146484375,
   0.039947509765625,
   -0.0294036865234375,
   0.041168212890625,
   -0.019256591796875,
   -0.006626129150390625,
   0.048431396484375,
   -0.0090179443359375,
   0.03973388671875,
   -0.016876220703125,
   -0.01505279541015625,
   -0.0017423629760742188,
   -0.005321502685546875,
   -0.053558349609375,
   -0.042694091796875,
   -0.0183563232421875,
   -0.0163726806640625,
   -0.0005903244018554688,
   0.0010042190551757812,
   0.03717041015625,
   0.01861572265625,
   0.006561279296875,
   -0.01500701904296875,
   0.034423828125,
   0.014190673828125,
   0.010955810546875,
   -0.0311737060546875,
   -0.0401611328125,
   -0.0206298828125,
   0.0200042724609375,
   0.04962158203125,
   0.03521728515625,
   0.01837158203125,
   -0.0201873779296875,
   0.00957489013671875,
   0.00962066650390625,
   0.04571533203125,
   -0.0010862350463867188,
   -0.005237579345703125,
   0.040069580078125,
   0.061553955078125,
   -0.00458526611328125,
   -0.0313720703125,
   -0.01477813720703125,
   0.032135009765625,
   -0.054840087890625,
   -0.0003445148468017578,
   -0.0045623779296875,
   0.0283203125,
   0.047515869140625,
   -0.0203704833984375,
   -0.003917694091796875,
   -0.0054168701171875,
   -0.007110595703125,
   -0.04010009765625,
   -0.028228759765625,
   0.0205535888671875,
   -0.02972412109375,
   0.023284912109375,
   -0.026702880859375,
   -0.0020904541015625,
   -0.01544189453125,
   0.0144805908203125,
   0.037078857421875,
   0.0131683349609375,
   -0.01538848876953125,
   -0.0189666748046875,
   -0.024810791015625,
   -0.04229736328125,
   -0.018524169921875,
   -0.0085296630859375,
   -0.00859832763671875,
   -0.0181732177734375,
   0.003467559814453125,
   0.0144500732421875,
   0.0242156982421875,
   0.003726959228515625,
   -0.00565338134765625,
   -0.0211944580078125,
   0.027191162109375,
   0.0127105712890625,
   0.05853271484375,
   0.0295562744140625,
   0.05145263671875,
   0.03521728515625,
   0.0124664306640625,
   -0.010589599609375,
   0.014862060546875,
   0.018035888671875,
   0.032958984375,
   -0.006717681884765625,
   -0.023590087890625,
   -0.040679931640625,
   0.024383544921875,
   -0.00010669231414794922,
   -0.048797607421875,
   -0.03912353515625,
   0.003261566162109375,
   -0.0255126953125,
   0.0303802490234375,
   -0.063232421875,
   -0.035064697265625,
   -0.03363037109375,
   0.016754150390625,
   0.0374755859375,
   0.032684326171875,
   -0.02886962890625,
   0.0112457275390625,
   -0.01256561279296875,
   0.008514404296875,
   0.005580902099609375,
   -0.004955291748046875,
   0.085693359375,
   -0.0645751953125,
   -0.0016908645629882812,
   0.04901123046875,
   0.01336669921875,
   0.0204315185546875,
   0.00030493736267089844,
   -0.0015850067138671875,
   0.08587646484375,
   -0.032196044921875,
   -0.047271728515625,
   -0.0012674331665039062,
   -0.042266845703125,
   -0.0506591796875,
   -0.052703857421875,
   0.04315185546875,
   0.0287017822265625,
   -0.0279693603515625,
   0.01477813720703125,
   -0.035247802734375,
   0.0489501953125,
   0.0261077880859375,
   -0.00010973215103149414,
   -0.01076507568359375,
   -0.03643798828125,
   0.043426513671875,
   -0.0032825469970703125,
   -0.0462646484375,
   -0.04437255859375,
   0.0582275390625,
   0.0296478271484375,
   -0.00785064697265625,
   -0.0210723876953125,
   -0.067138671875,
   -0.0303802490234375,
   -0.04595947265625,
   0.00019621849060058594,
   -0.0209503173828125,
   -0.01294708251953125,
   0.0265350341796875,
   0.0160064697265625,
   -0.050750732421875,
   0.040802001953125,
   -0.0161895751953125,
   -0.0270538330078125,
   -0.01605224609375,
   0.044036865234375,
   -0.0018396377563476562,
   -0.02166748046875,
   -0.03900146484375,
   -0.055999755859375,
   -0.03021240234375,
   -0.034149169921875,
   -0.00965118408203125,
   -0.01605224609375,
   0.034698486328125,
   0.0081939697265625,
   -0.026336669921875,
   -0.0034999847412109375,
   0.003620147705078125,
   0.007198333740234375,
   -0.0167694091796875,
   0.01251220703125,
   0.0142822265625,
   0.034820556640625,
   0.00762939453125,
   -0.035064697265625,
   0.0101470947265625,
   0.04150390625,
   -0.0178070068359375,
   -0.01055145263671875,
   0.03692626953125,
   -0.024627685546875,
   -0.0121612548828125,
   0.04559326171875,
   -0.025177001953125,
   -0.0160064697265625,
   -0.044281005859375,
   -0.0109100341796875,
   -0.00644683837890625,
   -0.0228729248046875,
   0.0202178955078125,
   0.0213470458984375,
   0.01050567626953125,
   0.00396728515625,
   0.0275726318359375,
   -0.01122283935546875,
   -0.0396728515625,
   -0.0021533966064453125,
   -0.0207977294921875,
   -0.00386810302734375,
   -0.04974365234375,
   0.002483367919921875,
   -0.0018291473388671875,
   -0.05322265625,
   -0.036102294921875,
   0.049163818359375,
   0.050018310546875,
   -0.01434326171875,
   0.0252227783203125,
   -0.00479888916015625,
   -0.047515869140625,
   0.03582763671875,
   -0.0031719207763671875,
   0.0011568069458007812,
   -0.0195465087890625,
   0.0491943359375,
   -0.00807952880859375,
   0.0233917236328125,
   -0.03369140625,
   0.0126800537109375,
   -0.043792724609375,
   0.03167724609375,
   0.02667236328125,
   -0.030914306640625,
   -0.052001953125,
   -0.011505126953125,
   0.045623779296875,
   -0.0053863525390625,
   -0.0272674560546875,
   0.024932861328125,
   -0.028167724609375,
   0.029937744140625,
   -0.01508331298828125,
   0.01134490966796875,
   -0.0236053466796875,
   -0.0019817352294921875,
   -0.063720703125,
   -0.020782470703125,
   -0.034759521484375,
   0.043060302734375,
   -0.0194549560546875,
   0.0189666748046875,
   0.02581787109375,
   0.00815582275390625,
   0.0180511474609375,
   -0.0361328125,
   -0.0169219970703125,
   -0.032867431640625,
   0.004428863525390625,
   -0.0297698974609375,
   0.00785064697265625,
   0.014556884765625,
   0.0220794677734375,
   0.0229949951171875,
   -0.02545166015625,
   0.053070068359375,
   -0.044952392578125,
   0.0166015625,
   -0.07598876953125,
   0.01122283935546875,
   0.021636962890625,
   0.00489044189453125,
   -0.0174560546875,
   -0.0014352798461914062,
   -0.046539306640625,
   0.035125732421875,
   0.0142974853515625,
   -0.0155181884765625,
   0.027618408203125,
   0.018157958984375,
   0.0303802490234375,
   0.0006103515625,
   0.01032257080078125,
   0.02935791015625,
   0.007259368896484375,
   -0.007717132568359375,
   0.034454345703125,
   0.02386474609375,
   0.0188751220703125,
   -0.016143798828125,
   0.0019140243530273438,
   -0.007350921630859375,
   0.027618408203125,
   0.025634765625,
   0.002593994140625,
   0.0221710205078125,
   -0.005428314208984375,
   -0.037841796875,
   -0.018646240234375,
   -0.0213623046875,
   0.0304718017578125,
   0.0386962890625,
   0.00841522216796875,
   0.0296783447265625,
   -0.0165863037109375,
   -0.0195465087890625,
   -0.015350341796875,
   0.0127716064453125,
   -0.03997802734375,
   0.01244354248046875,
   -0.0293121337890625,
   0.040069580078125,
   -0.0234222412109375,
   0.052154541015625,
   0.02386474609375,
   -0.0301055908203125,
   0.0021820068359375,
   -0.0254058837890625,
   -0.0202178955078125,
   -0.009674072265625,
   0.0369873046875,
   0.044769287109375,
   0.044036865234375,
   0.00042247772216796875,
   -0.026947021484375,
   -0.0384521484375,
   0.0091400146484375,
   0.042694091796875,
   0.01824951171875,
   -0.023345947265625,
   -0.03314208984375,
   -0.042999267578125,
   -0.02850341796875,
   -0.0169525146484375,
   -0.06536865234375,
   -0.030303955078125,
   -0.01157379150390625,
   0.042572021484375,
   -0.00952911376953125,
   -0.007450103759765625,
   0.0143280029296875,
   0.006195068359375,
   0.044708251953125,
   -0.0254058837890625,
   -0.06427001953125,
   0.0047607421875,
   0.039306640625,
   -0.007686614990234375,
   0.005275726318359375,
   -0.034698486328125,
   0.037353515625,
   0.028167724609375,
   -0.004055023193359375,
   0.049163818359375,
   -0.0005769729614257812,
   -0.02581787109375,
   -0.049224853515625,
   0.032989501953125,
   -0.05072021484375,
   -0.0302581787109375,

In [16]:
index.upsert(vectors=vectors, namespace='ns1')

{'upserted_count': 5}

In [ ]:
query = 'o ouro é de sendimentos da marinha?'

x = pc.inference.embed(
    'multilingual-e5-large',
    inputs=[query],
    parameters={'input_type': 'query'}
)

In [ ]:
results = index.query(
    namespace='ns1',
    top_k=3,
    vector=x[0].values,
    include_metadata=True,
    include_values=False
)

results

{'matches': [{'id': 'occurrence5',
              'metadata': {'text': 'Ouro disseminado em formações sedimentares '
                                   'de origem marinha, em conglomerados ricos '
                                   'em minerais pesados. Potencial para '
                                   'depósito do tipo placer ou paleoplacer.'},
              'score': 0.875868559,
              'values': []},
             {'id': 'occurrence1',
              'metadata': {'text': 'Ouro presente em veios de quartzo em uma '
                                   'formação hidrotermal. Observa-se alta '
                                   'concentração de ouro em zonas de fraturas '
                                   'e falhas.'},
              'score': 0.843479931,
              'values': []},
             {'id': 'occurrence3',
              'metadata': {'text': 'Ouro aluvial encontrado em depósitos de '
                                   'cascalho próximo a rios e córregos. Indica '
                                   'transporte e concentração secundária de '
                                   'ouro.'},
              'score': 0.841086268,
              'values': []}],
 'namespace': 'ns1',
 'usage': {'read_units': 6}}

### Adicionando livro como RAG

In [17]:
#!pip install pypdf

Collecting pypdf
  Downloading pypdf-5.5.0-py3-none-any.whl.metadata (7.2 kB)
Downloading pypdf-5.5.0-py3-none-any.whl (303 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 303.4/303.4 kB 16.2 MB/s eta 0:00:00
Installing collected packages: pypdf
Successfully installed pypdf-5.5.0

In [18]:
import pypdf

In [19]:
def chunk_text(text, chunk_size=500):
  #divide o texto em partes menores
  return[text[i:i+chunk_size] for i in range(0, len(text), chunk_size)]

In [21]:
with open('livro.pdf', 'rb') as f:
  reader = pypdf.PdfReader(f)
  text = ''

  for page_num in range(len(reader.pages)):
    page = reader.pages[page_num]
    text += page.extract_text()

In [22]:
chunks = chunk_text(text)

In [23]:
chunks[100]

'os do \ncampo de estudo discutido. \nJuntos com estes textos, esta o disponí -\nveis outros com enfoque mais geolo gico, \ncom descriço es de minerais, rochas, so-\nlos e estruturas. Um deles, que deve ser \nrecomendado, e  o de R.E. Goodman \n(1993, Engineering Geology: Rocks in En-\ngineering Construction ), que trata os \ngrandes grupos de rochas separadamen-\nte, reconhecendo que apresentam pro-\npriedades especí ficas e evoluço es distin-\ntas (por ex., no quesito alteração). A.C. \nMcLean e C.D. Gribbl'

In [24]:
data = []

#plano free da pinecone necessario menos tokens
for i, chunk in enumerate(chunks[:90], start=1):
  data.append({
      'id': f'chunk{i}',
      'text': chunk.strip()
  })

for chunk in data[:5]:
  print(chunk)

{'id': 'chunk1', 'text': 'Universidade de São Paulo \nInstituto de Geociências \nGeologia básica para engenheiros \nHorstpeter H. G. J. Ulbrich \nJose  B. de Madureira Filho \nEliane A. Del Lama \nLauro K. Dehira \nISBN:  978-65-86403-05-3 \nDOI:10.11606/9786586403053 \nSa o Paulo \n2023 Esta obra é de acesso aberto.  É permitida a reprodução parcial ou total desta obra, desde que citada a fonte e autoria, proibin do qualquer uso para fins \ncomerciais e respeitando a Licença Creative Commons indicada: Licença Creative Commons (CC'}
{'id': 'chunk2', 'text': 'BY-NC-ND 4.0) Atribuição-Não Comercial-Sem Deriva-\nções 4.0 Internacional.  \nPara mais informações, leia a política de privacidade do Portal de Livros Abertos da Agência de Bibliotecas e Coleções Digitais, Universidade de \nSão Paulo, SP, Brasil.   \n \n \nUniversidade de São Paulo \nReitor: Prof. Dr. Carlos Gilberto Carlotti Junior \nVice-Reitora: Profa. Dra. Maria Arminda do Nascimento Arruda \nInstituto de Geociências \nDiretor: Prof. Dr. Caetano Juliani \nVice-Diretor: Prof. Dr. Carlos Jose  Archanjo'}
{'id': 'chunk3', 'text': 'Diagramação \nLauro Kazumi Dehira \nCapa \nRodovia dos Tamoios (SP) \nFotografia: Luciane Kuzmickas \n_____________________________________________________________________________________ \nGeologia ba sica para engenheiros. Ulbrich, H.H.G.J., Madureira Filho, J.B., Del Lama, E.A.,  \nDehira, L.K. - Sa o Paulo:  IGc-USP, 2023. 267 p. \nISBN:  978-65-86403-05-3         \nDOI:10.11606/9786586403053 \n1. Geologia de Engenharia. 2. Maciço Rochoso. 3. Materiais Rochosos. I. Ulbrich,  \nHorstpeter. II. Madurei'}
{'id': 'chunk4', 'text': 'ra Filho, Jose . III. Del Lama, Eliane. IV. Dehira, Lauro.  \nGeologia ba sica para engenheiros. \n \nCDD 624.151 \n_____________________________________________________________________________________ \nServiço Te cnico de Biblioteca do Instituto de Geocie ncias da USP \nAUTORES \n \n \n \n \n \n \n \n \nHorstpeter Herberto Gustavo José Ulbrich , geo logo, doutor pela \nUniversity of California, Berkeley. Professor titular, e hoje aposentado, \ndo Instituto de Geocie ncias da USP. Tem experie ncia na a rea de G'}
{'id': 'chunk5', 'text': 'eoci-\ne ncias, com e nfase em Petrologia, atuando principalmente nos seguin-\ntes temas: rochas granitoides e alcalinas, Proterozoico, magmatismo, \ngeoquí mica analí tica, entalpias e entropias, gamaespectrometria.  \nhulbrich@usp.br \nJosé Barbosa de Madureira Filho, geo logo, doutor pela Universidade \nde Sa o Paulo. Professor-Doutor, aposentado do Instituo de Geocie ncias \nda USP. Desenvolveu pesquisas na a rea de propriedades fí sicas de mi-\nnerais; ministrou aulas em disciplinas de Geologia e M'}

In [25]:
embeddings = pc.inference.embed(
    "multilingual-e5-large",
    inputs=[d['text'] for d in data],
    parameters={
        "input_type": "passage"
    }
)

In [26]:
vectors = []
for d, e in zip(data, embeddings):
    vectors.append({
        "id": d['id'],
        "values": e['values'],
        "metadata": {'text': d['text']}
    })

index.upsert(
    vectors=vectors,
    namespace="ns1"
)

{'upserted_count': 90}

In [27]:
def info_geologia(query):
  x = pc.inference.embed(
      'multilingual-e5-large',
      inputs=[query],
      parameters={'input_type': 'query'}
  )
  results = index.query(
      namespace='ns1',
      top_k=3,
      vector=x[0].values,
      include_metadata=True,
      include_values=False
  )
  return results

In [28]:
query = 'o ouro ocorre em sedimentos de origem marinha?'
resposta = info_geologia(query)
resposta.matches[0].metadata['text']

'Ouro disseminado em formações sedimentares de origem marinha, em conglomerados ricos em minerais pesados. Potencial para depósito do tipo placer ou paleoplacer.'

In [29]:
# Função para iniciar o chat, mantendo o histórico
def chat():
    print("Iniciando chat com o modelo. Digite 'sair' para encerrar.")

    # Histórico de mensagens
    messages = [{"role": "system", "content": """
    Você é o Chat da Terra e do Universo e responde em português brasileiro
    perguntas sobre a previsão do tempo na Terra e do espaço próximo à Terra, além de informações sobre terremotos.
    """}]

    while True:
        user_message = input("Você: ")
        if user_message.lower() == "sair":
            print("Encerrando chat. Até a próxima!")
            break

        # Adicionar a mensagem do usuário ao histórico
        messages.append({"role": "user", "content": user_message})

        # Verificar se o tema é geologia
        if "geologia" in user_message.lower():
            # Chamar a função info_geologia para obter informações adicionais
            resposta = info_geologia(user_message)

            # Adicionar as informações de geologia ao histórico como contexto extra
            geologia_info = f"Informações adicionais sobre geologia: {resposta.matches[0].metadata['text']}"
            messages.append({"role": "system", "content": geologia_info})

        # Chamar a API com o histórico completo
        model_response = call_groq_api(messages)

        # Exibir a resposta do assistente
        display(model_response)
        if isinstance(model_response, pd.DataFrame):
            print("O model_response é um DataFrame.")
            texto_corrido = ""
            for index, row in model_response.iterrows():
                texto_corrido += f"Evento {index + 1}: Magnitude {row['mag']}, Local {row['place']}, Tempo {row['time']}\n"

            model_response = texto_corrido

        # Adicionar a resposta do modelo ao histórico
        messages.append({"role": "assistant", "content": model_response})

In [ ]:
chat()

Iniciando chat com o modelo. Digite 'sair' para encerrar.
Você: vai chover em sp?

'{"coord": {"lon": -46.6361, "lat": -23.5475}, "weather": [{"id": 803, "main": "Clouds", "description": "nublado", "icon": "04n"}], "base": "stations", "main": {"temp": 20.7, "feels_like": 21.02, "temp_min": 20.2, "temp_max": 21.36, "pressure": 1019, "humidity": 84, "sea_level": 1019, "grnd_level": 929}, "visibility": 10000, "wind": {"speed": 4.12, "deg": 150}, "clouds": {"all": 75}, "dt": 1747868552, "sys": {"type": 1, "id": 8394, "country": "BR", "sunrise": 1747820184, "sunset": 1747859412}, "timezone": -10800, "id": 3448439, "name": "S\\u00e3o Paulo", "cod": 200}'

Você: quantos anos vc tem

'{"coord": {"lon": -46.6361, "lat": -23.5475}, "weather": [{"id": 803, "main": "Clouds", "description": "nublado", "icon": "04n"}], "base": "stations", "main": {"temp": 20.67, "feels_like": 20.99, "temp_min": 20.2, "temp_max": 21.16, "pressure": 1019, "humidity": 84, "sea_level": 1019, "grnd_level": 929}, "visibility": 10000, "wind": {"speed": 4.12, "deg": 150}, "clouds": {"all": 75}, "dt": 1747868701, "sys": {"type": 1, "id": 8394, "country": "BR", "sunrise": 1747820184, "sunset": 1747859412}, "timezone": -10800, "id": 3448439, "name": "S\\u00e3o Paulo", "cod": 200}'

Você: ouro ocorre quando?

'{"coord": {"lon": -46.6361, "lat": -23.5475}, "weather": [{"id": 803, "main": "Clouds", "description": "nublado", "icon": "04n"}], "base": "stations", "main": {"temp": 20.67, "feels_like": 20.99, "temp_min": 20.2, "temp_max": 21.16, "pressure": 1019, "humidity": 84, "sea_level": 1019, "grnd_level": 929}, "visibility": 10000, "wind": {"speed": 4.12, "deg": 150}, "clouds": {"all": 75}, "dt": 1747868686, "sys": {"type": 1, "id": 8394, "country": "BR", "sunrise": 1747820184, "sunset": 1747859412}, "timezone": -10800, "id": 3448439, "name": "S\\u00e3o Paulo", "cod": 200}'

Você: sai da função

'{"coord": {"lon": -46.6361, "lat": -23.5475}, "weather": [{"id": 803, "main": "Clouds", "description": "nublado", "icon": "04n"}], "base": "stations", "main": {"temp": 20.68, "feels_like": 21.1, "temp_min": 19.94, "temp_max": 21.36, "pressure": 1019, "humidity": 88, "sea_level": 1019, "grnd_level": 929}, "visibility": 8000, "wind": {"speed": 2.57, "deg": 140}, "clouds": {"all": 75}, "dt": 1747868857, "sys": {"type": 2, "id": 2082654, "country": "BR", "sunrise": 1747820184, "sunset": 1747859412}, "timezone": -10800, "id": 3448439, "name": "S\\u00e3o Paulo", "cod": 200}'

Você: ouro ocorre quando?

'{"coord": {"lon": -46.6361, "lat": -23.5475}, "weather": [{"id": 803, "main": "Clouds", "description": "nublado", "icon": "04n"}], "base": "stations", "main": {"temp": 20.67, "feels_like": 20.99, "temp_min": 20.2, "temp_max": 21.16, "pressure": 1019, "humidity": 84, "sea_level": 1019, "grnd_level": 929}, "visibility": 10000, "wind": {"speed": 4.12, "deg": 150}, "clouds": {"all": 75}, "dt": 1747868701, "sys": {"type": 1, "id": 8394, "country": "BR", "sunrise": 1747820184, "sunset": 1747859412}, "timezone": -10800, "id": 3448439, "name": "S\\u00e3o Paulo", "cod": 200}'

Você: ouro ocorre quando? sai da função previsao tempo

'Não estou mais na função previsão do tempo. O ouro ocorre quando há uma combinação de condições atmosféricas que fazem com que a luz do sol seja refratada e dispersa, criando o efeito visual de um arco-íris com apenas uma cor, o ouro. Isso geralmente ocorre após uma chuva ou quando há gotículas de água suspensas no ar.'

Você: sair
Encerrando chat. Até a próxima!

### Disponibilizando o chat no gradio

In [31]:
#!pip install gradio

In [45]:
def response(message, history):
    messages = [{"role": "system", "content": """
    Você é o Chat da Terra e do Universo e responde em português brasileiro
    perguntas sobre a previsão do tempo na Terra e do espaço próximo à Terra, além de informações sobre terremotos.
    """}]

    # Adicionar o histórico anterior ao histórico de mensagens
    for user_msg, bot_msg in history:
        messages.append({"role": "user", "content": user_msg})
        messages.append({"role": "assistant", "content": bot_msg})

    # Adicionar a nova mensagem do usuário
    messages.append({"role": "user", "content": message})

    # Verificar se o tema é geologia
    if "geologia" in message.lower():
        resposta = info_geologia(message)
        geologia_info = f"Informações adicionais sobre geologia: {resposta.matches[0].metadata['text']}"
        messages.append({"role": "system", "content": geologia_info})

    # Obter a resposta do modelo
    model_response = call_groq_api(messages)

    # Se a resposta for um DataFrame, convertê-la para texto
    if isinstance(model_response, pd.DataFrame):
        texto_corrido = ""
        for index, row in model_response.iterrows():
            texto_corrido += f"Evento {index + 1}: Magnitude {row['mag']}, Local {row['place']}, Tempo {row['time']}\n"
        model_response = texto_corrido

    # Retornar a resposta como string para Gradio
    return model_response

In [33]:
import gradio as gr

In [ ]:
gr.ChatInterface(
    response,
    title='¬Chat da terra¬',
    textbox= gr.Textbox(placeholder="Digite sua msg aqui..."),
    type='messages'
).launch(debug=True)

It looks like you are running Gradio on a hosted a Jupyter notebook. For the Gradio app to work, sharing must be enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://178a6f310847b0456c.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7860 <> https://178a6f310847b0456c.gradio.live

In [34]:
from transformers import pipeline
import numpy as np

In [36]:
#necessário o HK_TOKEN para ler o modelo de descrição de áudio

transcritor = pipeline('automatic-speech-recognition',
                       model='openai/whisper-base',
                       generate_kwargs={"task":"transcribe", "language":"<|pt|>"})

def transcricao_audio(audio):
  sr, y = audio
  if y.ndim > 1:
    y = y.mean(axis=1)

  y = y.astype(np.float32)
  y /= np.max(np.abs(y))

  return transcritor({'sampling_rate': sr, 'raw': y})['text']

Device set to use cpu

In [46]:
with gr.Blocks() as demo:
    with gr.Tab("Chat da Terra e do Universo"):
        gr.ChatInterface(
            response,
            title='🌍☀️🌧️ Chat da Terra e do Universo',
            textbox=gr.Textbox(placeholder="Digite sua mensagem aqui..."),
            submit_btn=gr.Button("Enviar")

    )

    with gr.Tab("Assistente de áudio"):
        gr.Interface(
            transcricao_audio,
            gr.Audio(sources="microphone"),
            "text",
        )
demo.launch(debug=True)

/usr/local/lib/python3.11/dist-packages/gradio/chat_interface.py:339: UserWarning: The 'tuples' format for chatbot messages is deprecated and will be removed in a future version of Gradio. Please set type='messages' instead, which uses openai-style 'role' and 'content' keys.
  self.chatbot = Chatbot(

It looks like you are running Gradio on a hosted a Jupyter notebook. For the Gradio app to work, sharing must be enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://f01c3a42e135dbf234.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7862 <> https://f01c3a42e135dbf234.gradio.live

In [47]:
def responde_audio(audio):
    messages = [{"role": "system", "content": """
    Você é o Chat da Terra e do Universo e responde em português brasileiro
    perguntas sobre a previsão do tempo na Terra e do espaço próximo à Terra, além de informações sobre terremotos.
    """}]
    message = transcricao_audio(audio)


    # Adicionar a nova mensagem do usuário
    messages.append({"role": "user", "content": message})

    # Verificar se o tema é geologia
    if "geologia" in message.lower():
        resposta = info_geologia(message)
        geologia_info = f"Informações adicionais sobre geologia: {resposta.matches[0].metadata['text']}"
        messages.append({"role": "system", "content": geologia_info})

    # Obter a resposta do modelo
    model_response = call_groq_api(messages)

    # Se a resposta for um DataFrame, convertê-la para texto
    if isinstance(model_response, pd.DataFrame):
        texto_corrido = ""
        for index, row in model_response.iterrows():
            texto_corrido += f"Evento {index + 1}: Magnitude {row['mag']}, Local {row['place']}, Tempo {row['time']}\n"
            model_response = texto_corrido

    # Retornar a resposta como string para Gradio
    return model_response

In [50]:
with gr.Blocks() as demo:
    with gr.Tab("Chat da Terra e do Universo"):
        gr.ChatInterface(
            response,
            title='Chat da Terra e do Universo',
            textbox=gr.Textbox(placeholder="Digite sua mensagem aqui..."),
            submit_btn=gr.Button("Enviar")
    )

    with gr.Tab("Assistente de áudio"):
      gr.Interface(
          fn=responde_audio,
          inputs=gr.Audio(sources="microphone"),
          outputs="text",
          title="Assistente de áudio"
      )

demo.launch(debug=True)

/usr/local/lib/python3.11/dist-packages/gradio/chat_interface.py:339: UserWarning: The 'tuples' format for chatbot messages is deprecated and will be removed in a future version of Gradio. Please set type='messages' instead, which uses openai-style 'role' and 'content' keys.
  self.chatbot = Chatbot(

It looks like you are running Gradio on a hosted a Jupyter notebook. For the Gradio app to work, sharing must be enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://d07e11fa4574596531.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7862 <> https://d07e11fa4574596531.gradio.live

- **gTTS (Google Text-to-Speech)**

A gTTS é uma das bibliotecas mais populares para transformar texto em voz, usando a API do Google Translate. Ela é leve, fácil de instalar e oferece suporte a uma variedade de idiomas. A grande vantagem da gTTS é que é possível criar arquivos de áudio com apenas algumas linhas de código.

Exemplo:


```
pip install gtts

from gtts import gTTS
import os

# Texto que queremos converter em áudio
texto = "Olá! Este é um exemplo de conversão de texto para voz usando a biblioteca gTTS."

# Configuração da gTTS (idioma: português)
tts = gTTS(text=texto, lang='pt', slow=False)

# Salvando o arquivo de áudio
tts.save("exemplo_audio.mp3")

# Reproduzindo o áudio (opcional)
os.system("start exemplo_audio.mp3")  # No Windows, use "start"; no Mac, "afplay"; no Linux, "mpg321"
```

- **pyttsx3**

A biblioteca pyttsx3 permite a conversão de texto em voz offline, sem necessidade de conexão com a internet. Ela é uma ótima alternativa para quem precisa de uma solução local. Além disso, o pyttsx3 permite o controle da velocidade da fala e do volume. Com o pyttsx3, você tem um controle maior sobre a voz, e ele é ideal para ambientes que exigem TTS offline.

- **Amazon Polly**

A Amazon Polly é um serviço de texto para voz da AWS, capaz de gerar vozes naturais com excelente qualidade. Essa solução é paga, mas oferece vozes realistas e configurações avançadas, como controle de tom e pausas. Ela é amplamente utilizada em aplicações que demandam vozes mais naturais e com uma variedade maior de idiomas e sotaques. Para usar o Polly, é necessário ter uma conta AWS com permissões apropriadas para acessar o serviço.

- **Fala de IA do Azure**

A Fala de IA do Azure oferece um serviço robusto de TTS, suportando uma vasta gama de idiomas e permitindo configurações avançadas para gerar vozes naturais. É uma alternativa poderosa para empresas que já utilizam a infraestrutura da Microsoft. Para utilizar o Azure, você precisa configurar a conta e chave de acesso no portal da Azure. A integração com Python é feita usando a biblioteca azure-cognitiveservices-speech.

### Comparando modelos exemplo

```
import litellm
import os
from litellm import batch_completion_models

# Configurando as chaves de API
from google.colab import userdata
GROQ_API_KEY = userdata.get('GROQ_API_KEY')

# Fazendo a chamada para comparar as respostas
response = batch_completion_models(
    models=["groq/gemma2-9b-it",
            "groq/llama3-groq-70b-8192-tool-use-preview"],
    messages=[{"role": "user", "content": "Hey, how's it going"}]
)

# Exibindo os resultados
print(response)
```

### Extraindo embbedings pela biblioteca spacy exemplo

```
import spacy

# Carregar o modelo em português
nlp = spacy.load("pt_core_news_md")

# Lista de textos
data = [
    {
        "id": "occurrence1",
        "text": "Ouro presente em veios de quartzo em uma formação hidrotermal. Observa-se alta concentração de ouro em zonas de fraturas e falhas."
    },
    {
        "id": "occurrence2",
        "text": "Associação do ouro com sulfetos, especialmente pirita e arsenopirita, em ambiente de rochas metavulcânicas. Indica potencial para depósito orogênico de ouro."
    },
    {
        "id": "occurrence3",
        "text": "Ouro aluvial encontrado em depósitos de cascalho próximo a rios e córregos. Indica transporte e concentração secundária de ouro."
    },
    {
        "id": "occurrence4",
        "text": "Presença de ouro em formações de skarn associadas a intrusões ígneas graníticas. Indica formação relacionada a processos de metamorfismo de contato."
    },
    {
        "id": "occurrence5",
        "text": "Ouro disseminado em formações sedimentares de origem marinha, em conglomerados ricos em minerais pesados. Potencial para depósito do tipo placer ou paleoplacer."
    },
]

# Criar embeddings para cada ocorrência
embeddings = []
for occurrence in data:
    doc = nlp(occurrence["text"])
    embeddings.append({"id": occurrence["id"], "embedding": doc.vector})

# Resultados
for emb in embeddings:
    print(f"ID: {emb['id']}, Embedding: {emb['embedding'][:5]}...")  # Mostrando uma parte do embedding para simplificação
```

## Pontos importantes

- Interagir com modelos de linguagem de grandes dimensões (LLMs) utilizando a biblioteca litellm e a API GROQ;
- Criar um chatbot simples que se comunica com um modelo de LLM, armazenando o histórico da conversa para manter o contexto;
- Utilizar diferentes modelos de LLMs, como gemma2-9b-it e llama3-groq-70b-8192-tool-use-preview, para obter diferentes tipos de respostas;
- Obter informações do mundo real através de uma API externa, neste caso, a API de previsão do tempo OpenWeatherMap;
- Criar um dicionário para definir as ferramentas que o chatbot pode utilizar;
- Atualizar a função de chamada da API para integrar as ferramentas;
- Adicionar múltiplas ferramentas ao chatbot, incluindo APIs e funções que manipulam dados;
- Utilizar a biblioteca Pandas para carregar dados de um arquivo CSV e convertê-los para texto para o chatbot;
- Integrar ferramentas que usam APIs externas, arquivos CSV e outras bibliotecas como Pandas ao seu chatbot;
- Como utilizar a biblioteca Pinecone para fazer o embedding de textos e salvá-los em uma base de dados vetorial.
- Processo de carregar um livro em PDF para a base de conhecimento, dividindo-o em chunks de texto e realizando o embedding de cada um deles.
- Criar uma função para consultar uma base de dados vetorial e retornar o trecho de texto mais semelhante à pergunta do usuário;
- Integrar a função de consulta à base de dados ao chatbot, utilizando uma palavra-chave para determinar quando a consulta deve ser realizada;
- Adaptar a função de chatbot para atender as necessidades do Gradio, utilizando uma função response que recebe mensagens e histórico como entrada;
- Criar uma interface de chat com o Gradio, utilizando a função response para gerar as respostas do chatbot;
- Implementar a função ChatInterface do Gradio para criar a interface do chat, personalizando o título e o input do usuário.
- Criar uma segunda aba na sua aplicação utilizando o Gradio, adicionando funcionalidade de interação por voz;
- Utilizar o modelo Whisper da OpenAI para transcrever áudio em tempo real, utilizando a biblioteca Transformers;
- Subir a aplicação para o HuggingFace Spaces, tornando-a disponível para outros usuários;
- Adaptar o código para acessar as chaves de API diretamente do sistema, em vez de armazená-las no colab, garantindo segurança e acessibilidade;

### APIs e dados utilizados:

- https://openweathermap.org/api

acesso à previsão do tempo real-time

- https://console.groq.com/playground

acesso ao modelo llama

- https://app.pinecone.io/organizations

banco cloud dos embbedings

- https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json

alerta de tempestade solar

- https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_day.csv

extrai dados de sismos

- livro.pdf sobre geologia