# Correções de Redações automáticas

> Nota de 0 a 1000

In [ ]:
#pip install --upgrade datasets transformers

In [ ]:
from transformers import pipeline, create_optimizer
import pandas as pd
from datasets import Dataset, DatasetDict, load_dataset, ClassLabel

In [ ]:
model = pipeline('zero-shot-classification',
                 model='MoritzLaurer/mDeBERTa-v3-base-xnli-multilingual-nli-2mil7',
                 tokenizer = 'MoritzLaurer/mDeBERTa-v3-base-xnli-multilingual-nli-2mil7')

Uma alternativa promissora para contornar essa limitação é o Zero-Shot Learning (Aprendizado Zero-Shot). Este tipo de aprendizado permite que modelos de IA reconheçam e classifiquem novos rótulos que não estavam presentes durante o treinamento inicial. Isso é possível graças ao uso de descrições ou atributos dos novos rótulos, que são aprendidos de maneira a permitir que o modelo generalize para categorias inéditas.

No aprendizado Zero-Shot, os modelos são treinados com uma combinação de dados rotulados e metadados que descrevem os rótulos. Por exemplo, em uma tarefa de classificação de imagens, o modelo pode ser treinado não apenas com imagens de gatos e cavalos, mas também com descrições textuais dessas classes. Assim, quando o modelo se depara com uma nova classe, como "tigre", ele pode usar o conhecimento das descrições textuais para inferir as características do tigre, mesmo sem ter visto imagens dessa classe durante o treinamento.

In [ ]:
texto = 'Com o início da era digital, a capacidade de transmissão de informações cresceu apressuradamente, o que facilitou o contato com diversos assuntos, dentre eles a educação sexual . Entretanto, surgiram paralelamente algumas questões, das quais se destacam a preocupação com o momento adequado do ingresso do tema a vida do estudante, assim como de maneira antagônica, o aumento de casos de DST´S\\xa0\\xa0e gravidez indesejada nesse período, a qual leva a um maior questionamento sobre o começo desta pauta., A falta de comunicação sobre a sexualidade entre jovens no Brasil acarreta muitas das vezes\\xa0na inserção desses em um meio repleto de dúvidas, gerando a ocorrência de doenças sexualmente transmissíveis e de gravidez precoce. Com base nisso, muitos adolescentes buscam compreender melhor essas questões na internet, local onde se podem encontrar notícias falsas ou inadequadas para seu desenvolvimento, impedindo assim a correta compreensão do assunto, assim como a responsabilidade imposta por ele., Por outro lado, o diálogo em relação à sexualidade e seus tópicos é um tabu para pais e professores, que se sentem desorientados sobre a devida hora e os devidos critérios a serem tratados com os filhos e alunos, dificultando com que esses esclareçam suas dúvidas e entenda de maneira correta, o que levaria a conscientização da seriedade dessa discussão., Em virtude do que foi mencionado, as indagações a respeito divide várias opiniões e reflexões acima do que deve ser feito. É de extrema importância o Ministério da Educação, em parceria com o Ministério da Cidadania, implantar a educação sexual na matriz curricular estudantil dos jovens, através de aulas elaboradas e destinadas ao esclarecimento de perguntas, assim como palestras e programas com a intenção de propagar o conteúdo aos estudantes, contando com o suporte dos pais, funcionários e encarregados da rede de ensino no país, para que seja realizado constantemente.'

model(texto , candidate_labels = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'])

{'sequence': 'Com o início da era digital, a capacidade de transmissão de informações cresceu apressuradamente, o que facilitou o contato com diversos assuntos, dentre eles a educação sexual . Entretanto, surgiram paralelamente algumas questões, das quais se destacam a preocupação com o momento adequado do ingresso do tema a vida do estudante, assim como de maneira antagônica, o aumento de casos de DST´S\\xa0\\xa0e gravidez indesejada nesse período, a qual leva a um maior questionamento sobre o começo desta pauta., A falta de comunicação sobre a sexualidade entre jovens no Brasil acarreta muitas das vezes\\xa0na inserção desses em um meio repleto de dúvidas, gerando a ocorrência de doenças sexualmente transmissíveis e de gravidez precoce. Com base nisso, muitos adolescentes buscam compreender melhor essas questões na internet, local onde se podem encontrar notícias falsas ou inadequadas para seu desenvolvimento, impedindo assim a correta compreensão do assunto, assim como a responsabilidade imposta por ele., Por outro lado, o diálogo em relação à sexualidade e seus tópicos é um tabu para pais e professores, que se sentem desorientados sobre a devida hora e os devidos critérios a serem tratados com os filhos e alunos, dificultando com que esses esclareçam suas dúvidas e entenda de maneira correta, o que levaria a conscientização da seriedade dessa discussão., Em virtude do que foi mencionado, as indagações a respeito divide várias opiniões e reflexões acima do que deve ser feito. É de extrema importância o Ministério da Educação, em parceria com o Ministério da Cidadania, implantar a educação sexual na matriz curricular estudantil dos jovens, através de aulas elaboradas e destinadas ao esclarecimento de perguntas, assim como palestras e programas com a intenção de propagar o conteúdo aos estudantes, contando com o suporte dos pais, funcionários e encarregados da rede de ensino no país, para que seja realizado constantemente.',
 'labels': ['1', '5', '9', '6', '10', '3', '4', '2', '8', '7', '0'],
 'scores': [0.1422734409570694,
  0.09626700729131699,
  0.094220831990242,
  0.09221815317869186,
  0.09150050580501556,
  0.09114377945661545,
  0.08955563604831696,
  0.08833957463502884,
  0.08680029958486557,
  0.08445901423692703,
  0.04322177544236183]}

In [ ]:
#dataset = load_dataset('csv', data_files='/content/redacoes.csv')

df_pandas = pd.read_csv('/content/redacoes.csv')
df = Dataset.from_pandas(df_pandas)
df

Dataset({
    features: ['essay', 'score'],
    num_rows: 4570
})

In [ ]:
df.features

{'essay': Value(dtype='string', id=None),
 'score': Value(dtype='int64', id=None)}

In [ ]:
df['essay'][0], df['score'][0]

('A convivência com o ensino em uma escola pública , nos mostra \\xa0como a reforma do ensino médio é necessária, com o ensino precário, escolas quase desabando, falta de educadores,a formação de estudantes fica a \\xa0cada dia mais difícil., Atualmente o índice de jovens que procuram uma educação de qualidade é maior do que em todos os séculos , temos em vista que todos procuram a melhoria, tanto na estrutura da instituição como no ensino, muitos sonham em ser: médicos, professores,advogados, contadores, e assim sucessivamente., A solução seria a constatação de uma lei em prol dos estudantes, precisamos ser ouvidos, a voz dos jovens é a voz do futuro, queremos o ensino superior, queremos oportunidades em escolas públicas, escolas bem estruturada e profissionais competentes., Creio \\xa0que a reforma deveria ocorrer, pois o intuito é a melhoria (Que tipo de melhoria?,\\xa0assim todos os jovens teriam a oportunidade de serem profissionais de sucesso. O incentivo ( aos jovens é o que torna o país como sendo uma pátria de governantes justos e conhecedores de seus deveres .',
 4)

In [ ]:
df.to_pandas()

                                                  essay  score
0     A convivência com o ensino em uma escola públi...      4
1     O Brasil possui aproximadamente 425 mil polici...      5
2     O esporte é muito importante, as Olimpíadas, u...      8
3     O conceito de "banalidade do mal" da filósofa ...      8
4     Um dos assuntos que mais geram discussões atua...      5
...                                                 ...    ...
4565  Com o início da era digital, a capacidade de t...      6
4566  O feminicídio é o assassinato de uma mulher, a...      4
4567  Foram vrias as conquistas que as mulheres bras...      5
4568  Segundo o psicoterapeuta Ivan Carpelatto: “a v...      9
4569  Promulgada em 1988, a Constituição Federal a e...      7

[4570 rows x 2 columns]

In [ ]:
train_test = df.train_test_split(test_size=0.2, shuffle= False)
train_test

DatasetDict({
    train: Dataset({
        features: ['essay', 'score'],
        num_rows: 3656
    })
    test: Dataset({
        features: ['essay', 'score'],
        num_rows: 914
    })
})

In [ ]:
df = DatasetDict({
    'train': train_test['train'],
    'test': train_test['test']
})

df

DatasetDict({
    train: Dataset({
        features: ['essay', 'score'],
        num_rows: 3656
    })
    test: Dataset({
        features: ['essay', 'score'],
        num_rows: 914
    })
})

## Modelo de base para tokenização e aprendizado

In [ ]:
from transformers import AutoTokenizer

In [ ]:
checkpoint_modelo = 'Geotrend/distilbert-base-pt-cased'

tokenizador = AutoTokenizer.from_pretrained(checkpoint_modelo)

#### Exemplo tokenização e transformações com *attention*

In [ ]:
texto = df['train']['essay'][0]

tokens = tokenizador.tokenize(texto)
ids = tokenizador.convert_tokens_to_ids(tokens)
print(tokens, '\n\n', ids)

['A', 'con', '##viv', '##ência', 'com', 'o', 'ensino', 'em', 'uma', 'escola', 'pública', ',', 'nos', 'mostra', '\\', 'xa', '##0', '##com', '##o', 'a', 'reforma', 'do', 'ensino', 'médio', 'é', 'ne', '##ces', '##s', '##ária', ',', 'com', 'o', 'ensino', 'pre', '##c', '##ário', ',', 'escolas', 'quase', 'desa', '##band', '##o', ',', 'falta', 'de', 'edu', '##cado', '##res', ',', 'a', 'formação', 'de', 'estudantes', 'fica', 'a', '\\', 'xa', '##0', '##cada', 'dia', 'mais', 'difícil', '.', ',', 'Atualmente', 'o', 'índice', 'de', 'jovens', 'que', 'procura', '##m', 'uma', 'educação', 'de', 'qualidade', 'é', 'maior', 'do', 'que', 'em', 'todos', 'os', 'séculos', ',', 'tem', '##os', 'em', 'vista', 'que', 'todos', 'procura', '##m', 'a', 'melhor', '##ia', ',', 'tanto', 'na', 'estrutura', 'da', 'instituição', 'como', 'no', 'ensino', ',', 'muitos', 'son', '##ham', 'em', 'ser', ':', 'médicos', ',', 'professore', '##s', ',', 'ad', '##vog', '##ados', ',', 'conta', '##dores', ',', 'e', 'assim', 'su', '##ces', '##siva', '##mente', '.', ',', 'A', 'sol', '##ução', 'seria', 'a', 'consta', '##tação', 'de', 'uma', 'lei', 'em', 'pro', '##l', 'dos', 'estudantes', ',', 'precisa', '##mos', 'ser', 'ou', '##vidos', ',', 'a', 'voz', 'dos', 'jovens', 'é', 'a', 'voz', 'do', 'futuro', ',', 'quer', '##emos', 'o', 'ensino', 'superior', ',', 'quer', '##emos', 'oportunidades', 'em', 'escolas', 'públicas', ',', 'escolas', 'bem', 'estrutura', '##da', 'e', 'profissionais', 'compete', '##ntes', '.', ',', 'C', '##rei', '##o', '\\', 'xa', '##0', '##que', 'a', 'reforma', 'deveria', 'ocorre', '##r', ',', 'pois', 'o', 'int', '##uito', 'é', 'a', 'melhor', '##ia', '(', 'Que', 'tipo', 'de', 'melhor', '##ia', '?', ',', '\\', 'xa', '##0', '##ass', '##im', 'todos', 'os', 'jovens', 'teria', '##m', 'a', 'oportunidad', '##e', 'de', 'serem', 'profissionais', 'de', 'sucesso', '.', 'O', 'in', '##cent', '##ivo', '(', 'aos', 'jovens', 'é', 'o', 'que', 'torna', 'o', 'país', 'como', 'sendo', 'uma', 'p', '##át', '##ria', 'de', 'govern', '##antes', 'justo', '##s', 'e', 'con', '##he', '##cedo', '##res', 'de', 'seus', 'deve', '##res', '.']

 [46, 270, 24522, 2475, 303, 91, 13849, 348, 469, 5148, 5155, 25, 1125, 4201, 73, 5308, 759, 5563, 231, 77, 8008, 246, 13849, 19640, 144, 539, 2597, 206, 4354, 25, 303, 91, 13849, 1480, 415, 2854, 25, 16687, 8774, 3151, 4948, 231, 25, 5988, 203, 5725, 8294, 920, 25, 77, 11569, 203, 22157, 13510, 77, 73, 5308, 759, 6073, 608, 578, 7859, 27, 25, 12242, 91, 20373, 203, 18423, 220, 21237, 244, 469, 17937, 203, 16944, 144, 2695, 246, 220, 348, 1692, 463, 16426, 25, 1802, 383, 348, 3416, 220, 1692, 21237, 244, 77, 5915, 359, 25, 1813, 230, 9885, 240, 21600, 314, 286, 13849, 25, 6455, 385, 1948, 348, 510, 39, 17306, 25, 17575, 206, 25, 712, 22852, 2092, 25, 5719, 2669, 25, 81, 4832, 292, 2597, 12125, 576, 27, 25, 46, 2996, 10877, 4245, 77, 10673, 15832, 203, 469, 2900, 348, 955, 258, 441, 22157, 25, 15218, 2041, 510, 465, 17157, 25, 77, 4567, 441, 18423, 144, 77, 4567, 246, 5343, 25, 15894, 16539, 91, 13849, 3121, 25, 15894, 16539, 21388, 348, 16687, 13027, 25, 16687, 4577, 9885, 317, 81, 23395, 9010, 2541, 27, 25, 48, 8439, 231, 73, 5308, 759, 899, 77, 8008, 23312, 14665, 227, 25, 4844, 91, 6857, 24540, 144, 77, 5915, 359, 21, 7080, 1911, 203, 5915, 359, 44, 25, 73, 5308, 759, 23325, 1224, 1692, 463, 18423, 13121, 244, 77, 16843, 211, 203, 14346, 23395, 203, 7505, 27, 60, 205, 6686, 2704, 21, 2255, 18423, 144, 91, 220, 6247, 91, 1425, 314, 2371, 469, 92, 1350, 797, 203, 6579, 6661, 20371, 206, 81, 270, 1168, 24814, 920, 203, 1119, 4635, 920, 27]

In [ ]:
texto_codificado = tokenizador.decode(ids)
print(texto_codificado)

A convivência com o ensino em uma escola pública, nos mostra \ xa0como a reforma do ensino médio é necessária, com o ensino precário, escolas quase desabando, falta de educadores, a formação de estudantes fica a \ xa0cada dia mais difícil., Atualmente o índice de jovens que procuram uma educação de qualidade é maior do que em todos os séculos, temos em vista que todos procuram a melhoria, tanto na estrutura da instituição como no ensino, muitos sonham em ser : médicos, professores, advogados, contadores, e assim sucessivamente., A solução seria a constatação de uma lei em prol dos estudantes, precisamos ser ouvidos, a voz dos jovens é a voz do futuro, queremos o ensino superior, queremos oportunidades em escolas públicas, escolas bem estruturada e profissionais competentes., Creio \ xa0que a reforma deveria ocorrer, pois o intuito é a melhoria ( Que tipo de melhoria?, \ xa0assim todos os jovens teriam a oportunidade de serem profissionais de sucesso. O incentivo ( aos jovens é o que torna o país como sendo uma pátria de governantes justos e conhecedores de seus deveres.

In [ ]:
# camada de atenção entenderá qual é o significado do token ou palavra dentro do contexto
input_codificado = tokenizador(texto, return_tensors='tf')
print(input_codificado)

TensorFlow and JAX classes are deprecated and will be removed in Transformers v5. We recommend migrating to PyTorch classes or pinning your version of Transformers.

{'input_ids': <tf.Tensor: shape=(1, 271), dtype=int32, numpy=
array([[   11,    46,   270, 24522,  2475,   303,    91, 13849,   348,
          469,  5148,  5155,    25,  1125,  4201,    73,  5308,   759,
         5563,   231,    77,  8008,   246, 13849, 19640,   144,   539,
         2597,   206,  4354,    25,   303,    91, 13849,  1480,   415,
         2854,    25, 16687,  8774,  3151,  4948,   231,    25,  5988,
          203,  5725,  8294,   920,    25,    77, 11569,   203, 22157,
        13510,    77,    73,  5308,   759,  6073,   608,   578,  7859,
           27,    25, 12242,    91, 20373,   203, 18423,   220, 21237,
          244,   469, 17937,   203, 16944,   144,  2695,   246,   220,
          348,  1692,   463, 16426,    25,  1802,   383,   348,  3416,
          220,  1692, 21237,   244,    77,  5915,   359,    25,  1813,
          230,  9885,   240, 21600,   314,   286, 13849,    25,  6455,
          385,  1948,   348,   510,    39, 17306,    25, 17575,   206,
           25,   712, 22852,  2092,    25,  5719,  2669,    25,    81,
         4832,   292,  2597, 12125,   576,    27,    25,    46,  2996,
        10877,  4245,    77, 10673, 15832,   203,   469,  2900,   348,
          955,   258,   441, 22157,    25, 15218,  2041,   510,   465,
        17157,    25,    77,  4567,   441, 18423,   144,    77,  4567,
          246,  5343,    25, 15894, 16539,    91, 13849,  3121,    25,
        15894, 16539, 21388,   348, 16687, 13027,    25, 16687,  4577,
         9885,   317,    81, 23395,  9010,  2541,    27,    25,    48,
         8439,   231,    73,  5308,   759,   899,    77,  8008, 23312,
        14665,   227,    25,  4844,    91,  6857, 24540,   144,    77,
         5915,   359,    21,  7080,  1911,   203,  5915,   359,    44,
           25,    73,  5308,   759, 23325,  1224,  1692,   463, 18423,
        13121,   244,    77, 16843,   211,   203, 14346, 23395,   203,
         7505,    27,    60,   205,  6686,  2704,    21,  2255, 18423,
          144,    91,   220,  6247,    91,  1425,   314,  2371,   469,
           92,  1350,   797,   203,  6579,  6661, 20371,   206,    81,
          270,  1168, 24814,   920,   203,  1119,  4635,   920,    27,
           12]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 271), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

## Tokenizando a base de dados

In [ ]:
def tokenizar(dados):
  return tokenizador(dados['essay'], truncation=True)

df_tokens = df.map(tokenizar, batched=True, remove_columns=['essay'])

In [ ]:
df_tokens

DatasetDict({
    train: Dataset({
        features: ['score', 'input_ids', 'attention_mask'],
        num_rows: 3656
    })
    test: Dataset({
        features: ['score', 'input_ids', 'attention_mask'],
        num_rows: 914
    })
})

In [ ]:
df_tokens['train'].to_pandas()

,score,input_ids,attention_mask
0,4,"[11, 46, 270, 24522, 2475, 303, 91, 13849, 348...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,5,"[11, 60, 1497, 6656, 5124, 9019, 2782, 22218, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,8,"[11, 60, 290, 8465, 144, 3240, 1668, 25, 243, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,8,"[11, 60, 19131, 203, 15, 23380, 19311, 246, 28...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4,5,"[11, 2567, 441, 17363, 206, 220, 578, 2989, 78...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
...,...,...,...
3651,5,"[11, 46, 5148, 1802, 469, 17870, 7326, 230, 11...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3652,6,"[11, 60, 7234, 1280, 3543, 1802, 91, 2885, 203...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3653,4,"[11, 7855, 325, 4776, 4323, 1559, 14086, 13232...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3654,6,"[11, 60, 23602, 235, 326, 23949, 206, 203, 179...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3655,8,"[11, 15, 617, 10112, 755, 91, 8987, 1071, 77, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [ ]:
df_tokens['test'].to_pandas()

,score,input_ids,attention_mask
0,7,"[11, 60, 9133, 18342, 2294, 220, 13606, 1295, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,8,"[11, 599, 3088, 1306, 25, 22568, 2284, 2251, 8...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,4,"[11, 46, 15182, 20233, 16866, 2969, 14150, 81,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,7,"[11, 60, 10910, 303, 469, 7592, 1828, 21261, 1...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4,7,"[11, 1876, 91, 3222, 240, 1774, 9151, 359, 25,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
...,...,...,...
909,6,"[11, 3444, 91, 5764, 240, 452, 3543, 25, 77, 1...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
910,4,"[11, 60, 4880, 1235, 2011, 3575, 144, 91, 2370...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
911,5,"[11, 24848, 98, 8544, 243, 6634, 206, 220, 243...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
912,9,"[11, 4433, 91, 22999, 22429, 14533, 3507, 304,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
913,7,"[11, 2344, 14232, 8091, 348, 534, 25, 77, 2464...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

1. **Padding**

O padding é o processo de adicionar tokens (geralmente um token especial, como [PAD]) ao final ou ao início de uma sequência de texto para garantir que todas as sequências em um lote tenham o mesmo comprimento. Vamos entender isso a partir de um exemplo. Imagine que temos as seguintes sequências de texto:

* "Eu gosto de aprender"
* "Aprender é divertido"
* "Estudar"

Para processar essas sequências em um lote, precisamos que todas tenham o mesmo comprimento. Vamos supor que decidimos que todas devem ter 4 tokens. Aqui está como seria com padding, onde cada palavra é entendida como um token:

* "Eu gosto de aprender."
* "Aprender é divertido. [PAD]"
* "Estudar. [PAD] [PAD] [PAD]"

Dessa forma, todas as sequências têm o mesmo comprimento, facilitando o processamento em batch pelos modelos.

2. **Truncation**

O truncation é o processo de cortar uma sequência de texto para garantir que ela não exceda um determinado comprimento. Isso é útil quando temos textos muito longos e queremos garantir que todos os textos no lote tenham um comprimento máximo específico, economizando recursos computacionais e memória. Vamos utilizar o mesmo exemplo para entender como o truncation funciona.

Imagine que temos as seguintes sequências de texto:

* "Eu gosto de aprender"
* "Aprender é divertido"
* "Estudar"

Se decidirmos que o comprimento máximo é 3 tokens, o truncamento funcionaria assim:

* "Eu gosto de" (truncado de "Eu gosto de aprender.")
* "Aprender é" (truncado de "Aprender é divertido.")
* "Estudar" (permanece o mesmo porque já tem 1 token)

In [ ]:
df_tokens['train'].unique('score')

[4, 5, 8, 6, 10, 7, 1, 9, 3, 0, 2]

In [ ]:
scores = ClassLabel(names=[str(i) for i in range(11)])
scores

ClassLabel(names=['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], id=None)

In [ ]:
def mapear_labels (dados):
  dados['label'] = scores.str2int(dados['score'])
  return dados

df_tokens = df_tokens.map(mapear_labels, batched=True, remove_columns='score')

In [ ]:
df_tokens = df_tokens.cast_column('label', scores)

In [ ]:
df_tokens

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask', 'label'],
        num_rows: 3656
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask', 'label'],
        num_rows: 914
    })
})

## Preparando treinamento com modelo pré-treinado

In [ ]:
from transformers import TFAutoModelForSequenceClassification

In [ ]:
checkpoint_model = 'Geotrend/distilbert-base-pt-cased'

id2label = {0: '0', 1: '1', 2:'2', 3:'3', 4:'4', 5:'5', 6:'6', 7:'7', 8:'8', 9:'9',10:'10'}
label2id = {valor: chave for chave, valor in id2label.items()}
label2id

{'0': 0,
 '1': 1,
 '2': 2,
 '3': 3,
 '4': 4,
 '5': 5,
 '6': 6,
 '7': 7,
 '8': 8,
 '9': 9,
 '10': 10}

In [ ]:
model = TFAutoModelForSequenceClassification.from_pretrained(
    checkpoint_model,
    num_labels = df_tokens['train'].features['label'].num_classes,
    id2label = id2label,
    label2id = label2id,
    from_pt = True
)

In [ ]:
dados_train = model.prepare_tf_dataset(
    df_tokens['train'],
    shuffle = True,
    batch_size = 16,
    tokenizer = tokenizador
)

dados_validacao = model.prepare_tf_dataset(
    df_tokens['test'],
    shuffle = False,
    batch_size = 16,
    tokenizer = tokenizador
)

> **Principais Auto Classes**

1. AutoModel: é utilizado para carregar modelos de aprendizado profundo para diversas tarefas de NLP (Processamento de Linguagem Natural). Ele automaticamente seleciona o tipo de modelo correto (como BERT, GPT-2, RoBERTa, etc.) baseado no nome do modelo fornecido.

2. AutoTokenizer: carrega o tokenizador correspondente ao modelo. O tokenizador é responsável por converter o texto bruto em tokens que o modelo pode processar.

3. AutoConfig: carrega a configuração do modelo, que contém parâmetros importantes como o número de camadas, tamanho do vocabulário, entre outros. É útil para inspeção ou para quando se deseja modificar algumas configurações antes de carregar o modelo.

> **Auto Classes específicas**

Além das Auto Classes gerais, a biblioteca também oferece várias Auto Classes específicas, cada uma projetada para diferentes tarefas de NLP. Considere a seguir as principais classes específicas e suas utilizações:

1. AutoModelForSequenceClassification: utilizada para tarefas de classificação de sequência, como análise de sentimentos, detecção de spam e classificação de tópicos.

2. AutoModelForTokenClassification: utilizada para tarefas de classificação de tokens, como reconhecimento de entidade nomeada (NER) e marcação de partes do discurso (POS tagging)

3. AutoModelForQuestionAnswering: utilizada para sistemas de perguntas e respostas, onde o modelo responde a perguntas baseadas em um contexto fornecido.

4. AutoModelForSeq2SeqLM: utilizada para tarefas de tradução de linguagem, resumo de textos, e outras tarefas de sequência-para-sequência (seq2seq).

5. AutoModelForCausalLM: utilizada para tarefas de geração de texto, como modelos de linguagem autorregressivos (ex: GPT-2, GPT-3).

6. AutoModelForMaskedLM: utilizada para tarefas de modelagem de linguagem com máscaras, como preenchimento de palavras mascaradas em um texto (ex: BERT).

7. AutoModelForMultipleChoice: utilizada para tarefas de escolha múltipla, onde o modelo escolhe a resposta correta entre várias opções fornecidas.

8. AutoModelForNextSentencePrediction: utilizada para tarefas de predição da próxima sentença, como determinar se uma sentença segue logicamente outra.

## Transferindo aprendizado

In [ ]:
batch_size = 16
epochs = 5
batches_por_epoca = len(df_tokens['train']) // batch_size
total_passos_treino = int(batches_por_epoca * epochs)
taxa_aprendizado = 2e-5

otimizador, scheduler = create_optimizer(
    init_lr = taxa_aprendizado, num_warmup_steps = 0, num_train_steps = total_passos_treino
)

model.compile(optimizer = otimizador)

In [ ]:
model.fit(dados_train, validation_data = dados_validacao, epochs= epochs)

Epoch 1/5
228/228 [==============================] - 245s 966ms/step - loss: 1.8912 - val_loss: 1.6922
Epoch 2/5
228/228 [==============================] - 219s 962ms/step - loss: 1.6283 - val_loss: 1.5880
Epoch 3/5
228/228 [==============================] - 219s 961ms/step - loss: 1.5010 - val_loss: 1.5675
Epoch 4/5
228/228 [==============================] - 223s 977ms/step - loss: 1.3931 - val_loss: 1.5359
Epoch 5/5
228/228 [==============================] - 222s 974ms/step - loss: 1.2970 - val_loss: 1.5218

In [ ]:
resultados_avaliacao = model.evaluate(dados_validacao)
print(f'Loss: {resultados_avaliacao}')

58/58 [==============================] - 17s 298ms/step - loss: 1.5218
Loss: 1.521835207939148

Quando um modelo de IA realiza uma previsão, geralmente não fornece diretamente uma classe ou uma probabilidade. Em vez disso, são gerados um conjunto de valores numéricos chamados logits. Os logits podem ser qualquer número real, positivo ou negativo, e indicam a força e a direção da previsão do modelo para cada classe possível.

Para converter os logits em probabilidades compreensíveis, utiliza-se uma função de ativação. A mais comum é a softmax, que transforma os logits em valores entre 0 e 1, somando exatamente 1, tornando-os probabilidades (scores). Essas probabilidades indicam a confiança do modelo em cada classe.

Logits são importantes porque:

* Eles contêm informação sobre a confiança do modelo: logits mais altos indicam maior confiança.
* Facilitam o cálculo da métrica perda (Loss): funções de perda, como a entropia cruzada, usam logits para calcular o erro do modelo durante o treinamento.
* Servem como base para a decisão final: antes de aplicar a função de ativação, os logits ajudam a entender como o modelo chega às suas conclusões.

## Publicando modelo no HF

In [ ]:
from huggingface_hub import notebook_login

In [ ]:
notebook_login()

In [ ]:
from huggingface_hub import whoami

print(whoami())

In [ ]:
model.push_to_hub('distilbert-pt-cased-redacao-nota')

In [ ]:
tokenizador.push_to_hub('distilbert-pt-cased-redacao-nota')

## Construindo a aplicação

In [ ]:
import gradio as gr
from transformers import pipeline

In [ ]:
from transformers import TFAutoModelForSequenceClassification, AutoTokenizer
from transformers import TextClassificationPipeline

# Carrega tokenizer
tokenizer = AutoTokenizer.from_pretrained("vpsilvaa/distilbert-pt-cased-redacao-nota")

# Carrega modelo TensorFlow explicitamente
model = TFAutoModelForSequenceClassification.from_pretrained("vpsilvaa/distilbert-pt-cased-redacao-nota")

classificador = TextClassificationPipeline(
    model=model,
    tokenizer=tokenizer,
    framework="tf"
)

In [ ]:
def mostrar_resultado(texto):
    if len(texto) < 400:
        return 'O texto precisa ter no mínimo 400 caracteres'
    return int(classificador(texto)[0]['label']) * 100

In [ ]:
app = gr.Interface(
    fn = mostrar_resultado,
    inputs = gr.Textbox(label = 'Digite o texto'),
    outputs = gr.Textbox(label = 'Nota da redação'),
    title = 'Insira um texto para receber uma nota entre 0 e 1000'
)

app.launch()

## Pontos importantes

* Filtrar e selecionar modelos a partir do Hugging Face Hub;
* Carregar modelos pré-treinados da plataforma Hugging Face;
* Aplicar modelos Zero-Shot para classificar textos em categorias personalizadas;
* Construir aplicativos simples a partir do Gradio;
* Carregar e explorar uma base de dados CSV, convertendo-a para DataFrame para facilitar a análise;
* Dividir os dados em treino e teste usando train_test_split;
* Utilizar modelos pré-treinados e a função AutoTokenizer da biblioteca Transformers para tokenizar textos;
* Aplicar uma função de tokenização para gerar IDs e camadas de atenção;
* Usar o método map para processar grandes volumes de textos;
* Analisar a importância do parâmetro truncation=True para manter os tokens dentro do limite suportado pelo modelo;
* Identificar e confirmar o tipo da variável alvo score;
* Importar e utilizar ClassLabel da biblioteca datasets;
* Obter notas únicas e construir uma variável ClassLabels com labels de 0 a 10;
* Mapear valores inteiros das notas para labels textuais e remover coluna original score;
* Converter a coluna label para o formato ClassLabel;
* Carregar um modelo pré-treinado com AutoModelForSequenceClassification;
* Definir mapeamentos id2label e label2id para notas e labels;
* Preparar conjuntos de dados de treino e teste para o modelo no formato TensorFlow;
* Criar um otimizador a partir de hiperparâmetros do modelo;
* Compilar e treinar o modelo utilizando compile e fit;
* Configurar o ambiente no Google Colab para usar a GPU e acelerar o treinamento de um modelo;
* Avaliar modelos com model.evaluate e obter da métrica de perda (loss);
* Criar uma conta na Hugging Face e gerenciar tokens de acesso;
* Salvar e exportar modelos treinados na Hugging Face com push_to_hub e tokenizador associado;